### ISSUE TITLE
another vtype layout bug

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#101]
We have two "vtype layout" tables (one without ediv and one with), and one "vtype register format" table (without ediv).  An earlier pull request from me fixed typos in the vtype layout tables with the reserved bits line, but I missed the vtype register format table which has the same bug.  This could maybe be placed in a separate file and included so we don't have two almost identical copies of the same table.

**Comment by kasanovic** [comment]
Good idea - factored into separate file.
