### ISSUE TITLE
Does special case of vl=0  apply to destination scalars (element[0] of vector register)

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-v-spec#103]
In 3.7. Vector Length Register vl:

Elements in the destination vector with indices >= vl are zeroed during execution of a vector instruction. 
As a special case, when vl=0, no elements are updated in the destination vector.

For the vmv.s.x instruction the "trailing" elements in the destination vector register ( 0 < index < VLEN/SEW) are zeroed.
For vredop family this is not stated but likely the case.

Is the scalar destination written even when vl = 0 for the vredop family, and thus the "trailing" elements zeroed or is the vector register left unchanged?

And what of the vmv.s.x and vfmv.s.f instructions when vl = 0? no-ops?

**Comment by kasanovic** [comment]
redop does zero elements 1 and above, and np on vl=0.
nop for vmv.s.x and vmv.s.f when vl=0.
Updated text.
