### ISSUE TITLE
MAC resource resue

### ISSUE THREAD

**Issue by HKLee2040** [riscv/riscv-v-spec#104]
Considering 16-bit integer multiply-add instruction, we have:
vd = vd + vs2*vs1

If the SEW is changed to be 8-bit, the throughput can be double, e.g. 16bx16b 64MAC/cycle and 8bx8b 128MAC/cycle

Can we have an instruction, for example
acc[i] += c0 x v0[i] + c1 x v1[i] + c2 x v2[i] + c3 x v3[i]
I think these 4 8bx8b resource might have better utilization on 16bx16b MAC resource, and the throughput could be better.

**Comment by kasanovic** [comment]
This would require additional vector register sources. (5 total + 1 if renaming/ECC)

A related instruction is available via EDIV using vdot instruction.
I added examples to show this:

# Dot product, SEW=32, EDIV=4
vdot.vv vd, vs2, vs1, vm # vd[i][31:0] += vs2[i][31:24] * vs1[i][31:24]
                                            + vs2[i][23:16] * vs1[i][23:16]
                                            + vs2[i][15:8] * vs1[i][15:8]
                                            + vs2[i][7:0] * vs1[i][7:0]
