### ISSUE TITLE
encoding of fault-only-first stores?

### ISSUE THREAD

**Issue by Websolder** [riscv/riscv-v-spec#107]
In section 7.8 we have instruction of unit-stride fault-only-frist segment stores ( vsseg<nf>{b,h,w,e}ff.v ), but unit-stride fault-only-first stores are not mentioned before, and the corresponding encoding of sumop[4:0] field of these instructions is not provided in section 7.2 too.

I guess this is just a typo, or the encoding of their sumop[4:0] field is also 10000 (similarly to unit-stride fault-only-first loads).

**Comment by kasanovic** [comment]
This was as typo.
