### ISSUE TITLE
mixed-precision operation

### ISSUE THREAD

**Issue by HKLee2040** [riscv/riscv-v-spec#108]
Following the issue #104 , 

Dot product, SEW=32, EDIV=4
vdot.vv vd, vs2, vs1, vm # vd[i][31:0] += vs2[i][31:24] * vs1[i][31:24] + vs2[i][23:16] * vs1[i][23:16] + vs2[i][15:8] * vs1[i][15:8] + vs2[i][7:0] * vs1[i][7:0]

Can it support 8bit x 16bit vdot, for example?
vd[i][31:0] += vs2[i][31:16] * vs1[i][15:8] + vs2[i][15:0] * vs1[i][7:0]

**Comment by kasanovic** [comment]
Can load 8b memory values into 16b elements, and do 16bx16b vdot.  This gives same result as explicit 8bx16b mul, though might not be as efficient in terms of multiplier array utilization.  Explicit 8bx16b vdot could be added as new instruction extension to reduce multiplier array requirements.
