### ISSUE TITLE
example algoritm problematic

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-v-spec#109]
the narrative for **13.5. Vector Single-Width Scaling Shift Instructions** clearly defines the function, however the formula in the examples does not explicitly reference the sign/zero extension. Rounding that would carry into or our of the high order bit are problematic.

consider SEW=8:
 value in the element X'FF' vssrl by 1 should be X'80' , formula yields X'00'
 value in the element X'7F' vssra by 1 should be X'40' , formula yields X'C0'

I couldn't come up this an obviously good notation to express the required value extension but perhaps this will do:

 # For vxrm=rnu, round = 1 << (src2-1)
 # Scaling shift right logical
 vssrl.vv vd, vs2, vs1, vm   # vd[i] = (zero_extend(vs2[i]) + round)>>vs1[i]
 vssrl.vx vd, vs2, rs1, vm   # vd[i] = (zero_extend(vs2[i]) + round)>>x[rs1]
 vssrl.vi vd, vs2, imm, vm   # vd[i] = (zero_extend(vs2[i]) + round)>>imm

 # Scaling shift right arithmetic
 vssra.vv vd, vs2, vs1, vm   # vd[i] = (sign_extend(vs2[i]) + round)>>vs1[i]
 vssra.vx vd, vs2, rs1, vm   # vd[i] = (sign_extend(vs2[i]) + round)>>x[rs1]
 vssra.vi vd, vs2, imm, vm   # vd[i] = (sign_extend(vs2[i]) + round)>>imm

**Comment by aswaterman** [comment]
The text has been changed to use the `roundoff` function, but this issue persists.  We should perhaps define `roundoff_unsigned` and `roundoff_signed` functions.  I'll make a PR.

**Comment by David-Horner** [comment]
Looks good to me.
The roundoff text is much better than original.
And now comprehensive with the signed/unsigned .
Thanks.

**Comment by aswaterman** [comment]
Cool, thanks for the review.
