### ISSUE TITLE
Do not put pdf files under version control

### ISSUE THREAD

**Issue by go-sc** [riscv/riscv-v-spec#119]
It looks like continuous integration introduced in 9ae3c3426eec9ae1ad1a71887b7365db2291c47f creates a new branch `gh-pages` in the repository.
pdf-files are not git-friendly. Every commit from now on that updates file `v-spec.pdf` forces git to store a new copy of this file in a repository history.
The V-spec is under active development, which means that specification edits will occupy more and more storage space.

**Comment by drom** [comment]
Travis CI flow with deployment to the Github pages was introduced to create HTML / PDF files from the specs merged to the `master` branch. By default, Github pages service stores all files in `gh-pages` branch. I don't know a better, opensource, free and automatic way of releasing PDF documents. Any suggestions?

**Comment by aswaterman** [comment]
We could do it the way I did for riscv-isa-manual, where deployment creates a release, but does not push to a branch.

**Comment by drom** [comment]
But then HTML/PDF will not be published on the Web server.

**Comment by go-sc** [comment]
GitHub releases feature is suitable for publishing binary files for (sort of) stable releases.
Anyone willing to create a pdf file for a certain commit can do it with a simple makefile that calls Asciidoctor with proper arguments.
HTML version of .adoc files generated by GitHub is OK, so probably there was no need in continuous integration at all.

**Comment by drom** [comment]
I have removed Travis-CI config, flow and `gh-pages` branch. https://github.com/riscv/riscv-v-spec/commit/f51e1b315fd63053942744063087f729ada49fbd
HTML / PDF are not stored in this repo.

**Comment by go-sc** [comment]
Yes, closing.
Thank you.
