### ISSUE TITLE
Use case for vfwredosum.vs?

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#123]
This instruction is defined to sum the elements in vs2 in the narrower format, then add the result to the wider format.  I believe that means when this instruction is used in a strip-mine loop, the result is VLEN-dependent.  (At the extremes, when VLEN = ELEN, all math is performed in the wider format, whereas when VLEN = ELEN * AVL, all math is performed in the narrow format.)

This doesn't seem very useful, so am I missing something?  Wouldn't it be more useful to define the instruction to perform all arithmetic in the wider format?  Then, it could be used to auto-vectorize a loop like

    double sum = 0.0;
    float f[n] = ...;
    for (i = 0; i < n; i++)
      sum += f[i];

**Comment by kasanovic** [comment]
OK, TG agrees.
