### ISSUE TITLE
For vfredosum.vs, define that vs1[0] is added first

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#124]
It isn't explicitly stated whether vs1[0] is added at the front or the back, but other sections imply that it's added at the back.  I think that for the instruction to be useful for autovectorization, it must be defined to be added at the front, i.e., to compute `vs1[0] + vs2[0] + ... + vs2[vl-1]`.

**Comment by kasanovic** [comment]
TG agrees.
