### ISSUE TITLE
Do vsetvl{i} instructions reset vstart to 0?

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#127]
One reading of the spec implies the answer is yes ("All vector instructions are defined [...] to reset the vstart CSR to zero at the end of execution").

But without the ellipsis, the spec sounds like it's only referring to vector instructions that write vector registers ("All vector instructions are defined to begin execution with the element number given in the vstart CSR, leaving earlier elements in the destination vector undisturbed, and to reset the vstart CSR to zero at the end of execution").

I think either definition is fine.  If vsetvl resets vstart, that means context-switching code needs to restore vl/vtype before restoring vstart, but that seems OK.

**Comment by vbx-glemieux** [comment]
as a programmer, after issuing a vsetvl, i would expect the next vector
compute instruction to operate on elements 0 to vl-1. hence, it should
clobber vstart. the role of vstart is to resume execution of an interrupted
vector instruction. after executing vsetvl, i expect not to resume, but to
initiate a new instruction.

so, i vote "yes" to reset vstart to 0 after vsetvl{i}

g
