### ISSUE TITLE
can vector instruction with vl==0 be dropped completely as NOP?

### ISSUE THREAD

**Issue by solomatnikov** [riscv/riscv-v-spec#130]
E.g. vector load can cause a PMP or page table exception even if it doesn't update any register state.

Also, instructions can update stats counters and have other side effects.

**Comment by aswaterman** [comment]
According to the current spec, even if vl=0 (or vstart >= vl), the elements at vl and beyond still need to be written with zero.

But no memory should be accessed, so there should be no page faults or access exceptions.

**Comment by solomatnikov** [comment]
https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#vector-length-register-vl

> As a special case, when vl=0, no elements are updated in the destination vector.

This sentence says no elements are updated when vl==0

**Comment by aswaterman** [comment]
Ah, my mistake, what I said is only true for the vstart >= vl case.

**Comment by vbx-glemieux** [comment]
what if vl=0 and vstart=0 ?

(sorry not trying to be pedantic, but this seems to be a plausible case
that has ambiguity right now)

guy

**Comment by aswaterman** [comment]
Sidestepping your question, I'm wondering what the merits are of treating vstart >= vl differently than vl = 0.  An alternative is to keep all elements intact whenever vstart >= vl, which would subsume the vl = 0 case.  Not sure what the downsides might be.

**Comment by kasanovic** [comment]
Closed by pull request #133.
