### ISSUE TITLE
What are the reset values of vl, vtype, etc?

### ISSUE THREAD

**Issue by solomatnikov** [riscv/riscv-v-spec#137]

**Comment by aswaterman** [comment]
My opinion is that, as long as vtype.vill is 1 after reset, the other fields and registers don’t matter, and can even be inconsistent (e.g. vl > MAXVL). If vtype.vill is 1, then the vector unit won’t be usable until vsetvl is executed, which will bring the system into a consistent state.

**Comment by kasanovic** [comment]
I agree with view that vtype.vill should be set to 1 on reset.

**Comment by kasanovic** [comment]
Maybe could be weaker requirement that state has to be a supported vtype, or vtype.vill=1.

**Comment by aswaterman** [comment]
Weaker requirement seems OK (so either vill=1 and all other state is unspecified and possibly inconsistent, or vill=0, vtype supported, and state is consistent, i.e. vl <= VLMAX).
