### ISSUE TITLE
16.1: Vector Mask-Register Logical Instructions: bitwise or mask-element-wise?

### ISSUE THREAD

**Issue by jsgray** [riscv/riscv-v-spec#139]
I could not tell from the spec / example notation whether mask-register logic instructions operate bitwise or mask-element-wise.

For example, when SEW=8 LMUL=1 => MLEN=8, and if VLEN=64, and if we have
v1 = 0x88.77.66.55.44.33.22.11 (as a mask: 0.1.0.1.0.1.0.1)
v2 = 0x0f.0f.0f.0f.0f.0f.0f.0f (as a mask: 1.1.1.1.1.1.1.1)
after vmand.mm v3,v1,v2
is v3 == 0x08.07.06.05.04.03.02.01 or 0x00.01.00.01.00.01.00.01?

**Comment by aswaterman** [comment]
The pseudocode (e.g. `vd = vs2 & vs1` for `vmand`) suggests a bitwise operation, which seems like the right definition to me.  The alternative mask-element-wise variant that produces only 0 or 1 is more expensive to implement but doesn't seem to benefit software.  I'll PR a clarification, and the others will let us know if I'm wrong :)

**Comment by kasanovic** [comment]
It was intended to be bitwise to reuse the hardware for logical operations, and as Andrew points out, software should not particularly care.
