### ISSUE TITLE
Do not write 0 after vl

### ISSUE THREAD

**Issue by go-sc** [riscv/riscv-v-spec#14]
Section 5:
> The active vector length in `vl` determines the number of elements processed by each vector instruction. Instructions producing vector shape results, write zero to destination vector elements past the end of `vl`.

Any motivation on that?
`vl` is supposed to be the number of elements that are going to be changed. The quoted statement implies counter-intuitive side effect going past `vl`.
Elements past `vl` can just be left untouched and used later with different `vl` value.

**Comment by vbx-glemieux** [comment]
see https://github.com/riscv/riscv-v-spec/issues/13#issuecomment-431079152

**Comment by colinschmidt** [comment]
Closing in favor of keeping discussion on this issue in one place #13
