### ISSUE TITLE
vadc and vsbc behaviour under EDIV>1

### ISSUE THREAD

**Issue by jnk0le** [riscv/riscv-v-spec#143]
Those instructions reads and writes implicit mask in v0.
EDIV extension defines that the masking is done at the element level and doesn't mention vadc/vsbc in not affected list.

How are those instructons intended to operate when EDIV>1?

**Comment by kasanovic** [comment]
Due to issue #155 , might be redefining adc/sbc, but EDIV issue remains.
Simplest solution is to cause illegal instruction exception for adc with EDIV>1, but needs more thought.
