### ISSUE TITLE
get element's index in vector register

### ISSUE THREAD

**Issue by rednoah91** [riscv/riscv-v-spec#146]
For example, I would like to find the index of t0 in v0. 
I use:
vseq.vx v2, v0, t0
vmfirst.m t1, v2

Do we have an instruction to return the index directly : )?

**Comment by kasanovic** [comment]
No, we don't.   The vmfirst can be chained/fused and can early out, so  there's not too much to be gained by adding a special instruction for this case.  In application areas where this operation is common, it might be worth considering adding an extension.

**Comment by rednoah91** [comment]
Got it~ thx : )
