### ISSUE TITLE
vext.x.v / vfmv.f.s asymmetry

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#154]
The integer variant can extract any element, based upon `x[rs1]`, whereas the floating-point variant can only extract element 0.  These should probably be made symmetrical, either by changing the integer variant to only allow extraction of element 0, or by changing the floating-point variant to allow extraction of any element.

I favor the former option for its simplicity.  vext was provided largely for allowing a debugger to read out vector registers without touching memory, but a debugger can do that with vslide1down instead.  And in application code, vext can be emulated with vslidedown or vrgather with vl=1, followed by extracting element 0.

**Comment by JerryShih** [comment]
Could we add the same function as vext for floating value?
How to emulate vext using vslidedown or vrgather? It's easier to use vext with your index value.

**Comment by aswaterman** [comment]
Easier, yes, but not necessarily much faster.  In many implementations, vext will cause a loss of decoupling, which will have a more significant performance impact than the additional cost of the `vslidedown`.

**Comment by aswaterman** [comment]
Related issue: although I still think we should redefine vext.x.v extract element 0 rather than element x[rs1], if we choose to go the opposite direction and allow extraction from any element position, we should consider redefining these instructions to operate on register groups instead of registers.
