### ISSUE TITLE
VLMAX definition

### ISSUE THREAD

**Issue by solomatnikov** [riscv/riscv-v-spec#156]
Is `VLMAX` defined as a constant or does it depend on `LMUL`?

One part of the spec seem to imply `VLMAX` is a constant, other parts imply it depends on `LMUL`.

**Comment by aswaterman** [comment]
It's defined to be `VLMAX = LMUL * VLEN/SEW`.  Where is it implied to be invariant of LMUL?

**Comment by solomatnikov** [comment]
I think `VLMAX` should be defined first before it is used in the text.
