### ISSUE TITLE
vssrl&vssra vs vnclipu&vnclip

### ISSUE THREAD

**Issue by wwang0** [riscv/riscv-v-spec#159]
vnclipu&vnclip seems just be the narrowing version of vssrl&vssra, why don't we rename them as vnssrl&vnssra?   In my view, vnclipu&vnclip is more close to right shift instructions with saturating and rounding  than a conventional clip.

Thanks

**Comment by chuanhua** [comment]
The main function of vnclipu and vnclip is the clipping part from both ends of a SEW-size-determined value range, unsigned and signed.  The term of "narrowing" does not convey how the "narrowing" operation is performed to reduce a 2*SEW-sized value into a SEW-sized value range. So I think the original names are appropriate.

**Comment by kasanovic** [comment]
Thanks for explanation @chuanhua

**Comment by wwang0** [comment]
@chuanhua , @kasanovic   My point is using clip loses 'shift right' meaning. As for "The term of "narrowing" does not convey how the "narrowing" operation is performed to reduce a 2*SEW-sized value into a SEW-sized value range",  actually the first s(saturating and rounding) + n tells it. 

I know there is no perfect name, so the current names seems ok, but just share my opinions here.
