### ISSUE TITLE
Not all instructions that take mask register as destination operand are prefixed by vm*

### ISSUE THREAD

**Issue by wwang0** [riscv/riscv-v-spec#160]
a few instructions that take mask register as destination operand are not prefixed by vm*:
vseq, vsne, vsltu, vslt, vsleu, vsle, vsgtu, vsgt, vfeq, vfle, vford, vflt, vfne, vfgt.

To make names more meaningful, I suggest to rename them as:
vmseq, vmsne, vmsltu, vmslt, vmsleu, vmsle, vmsgtu, vmsgt, vmfeq, vmfle, vmford, vmflt, vmfne, vmfgt.

Then we have unified vector master instructions naming convention:
vmops.vv
vmops.vx
vmops.vi
vmops.vf
vmops.mm
vmops.m

**Comment by wwang0** [comment]
@aswaterman , @kasanovic , any comments? thanks

**Comment by aswaterman** [comment]
I agree with prefixing the comparisons with `vm`.

**Comment by wwang0** [comment]
Thanks @aswaterman for your reply . and i will prepare a pull request for review.
