### ISSUE TITLE
Consider adding vfrsub and vrdiv

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#162]
For FP/int symmetry. (This is posted on DaveP’s behalf.)

**Comment by kasanovic** [comment]
Group agreed to add these in encoding.

**Comment by kasanovic** [comment]
Integer reverse divide would really require 4 new instructions (divide/remainder)*(signed/unsigned).
No good opcode space to add these - suggest they are not critical and decided not to include.  Vector splat and regular vector-vector divide/remainder gets same effect with not much overhead given expected performance of integer divide.

**Comment by aswaterman** [comment]
Agreed.
