### ISSUE TITLE
new or deprecated instruction? vsbc.vi vd, <vs>, <imm>

### ISSUE THREAD

**Issue by simon5656** [riscv/riscv-v-spec#164]
We are using a toolchain from github that includes vectors and it has the instruction 
    vsbc.vi vd, <vs>, <imm>
this instruction is not in the 0.7 spec

does this instruction exist or not?

**Comment by aswaterman** [comment]
This instruction shouldn't exist for the same reason that vsub.vi doesn't exist.  Looks like it was included by accident and removed from the spec on Feb. 10.
