### ISSUE TITLE
decodes of vmsof and vmsif

### ISSUE THREAD

**Issue by simon5656** [riscv/riscv-v-spec#167]
we are using a toolchain from github which appears to swap the decodes of vdot and vdotu instructions when compared to the specification 0.7

pls confirm that the decodes of these instructions in the specification is in fact correct.

**Comment by simon5656** [comment]
sorry typo above there are two sets of swaps:
vmsof and vmsif 

and 
vdot and vdotu 

pls confirm that the decodes in the specification 0.7 are correct or not.

**Comment by aswaterman** [comment]
The spec is the authority, so presumably it is the toolchain that is wrong.

**Comment by simon5656** [comment]
thanks
