### ISSUE TITLE
specification of widening vector operations

### ISSUE THREAD

**Issue by simon5656** [riscv/riscv-v-spec#168]
With respect to widening vector operations, the specification 0.7 says that:
_The destination vector register group cannot overlap a source vector register group (including the mask register if masked), otherwise an illegal instruction exception is raised_

Does this constraint apply to the first source argument of an operation where that argument is also widened by the same amount? (e.g. vwaddu.wv)?

**Comment by kasanovic** [comment]
Should not. Will clarify.
