### ISSUE TITLE
Can vslide index be negative?

### ISSUE THREAD

**Issue by go-sc** [riscv/riscv-v-spec#17]
Can `rs2` (start index) value be negative?
How do we effectively perform circular shift of vector elements?

**Comment by colinschmidt** [comment]
Its possible to perform a general rotate with the `vrgather` instruction assuming a few additional instructions to generate the index vector.

`vrgather` was added to the encoding (previously only in the text) in a1e5672

**Comment by go-sc** [comment]
It looks like the question in the title has not been explicitly answered (yes/no).
Anyway, it was restated in other words in #45.
