### ISSUE TITLE
what should happen for vector loads and stores when vstart is non-zero

### ISSUE THREAD

**Issue by simon5656** [riscv/riscv-v-spec#170]
It is not clear from the specification what should happen for vector loads and stores when vstart is non-zero

There is a need for a clear explanation of how the first load address is calculated for each of the three addressing modes in this case.

**Comment by simon5656** [comment]
We assume the address is calculated for elements with element number greater than 0 in the same way irrespective of current vstart.

**Comment by aswaterman** [comment]
Element N used address (rs1 + N * stride), regardless of vstart.
