### ISSUE TITLE
about vid.v

### ISSUE THREAD

**Issue by davetw** [riscv/riscv-v-spec#178]
Hi all,

Firstly, what's the use case of vdiv? to know which elements been masked?
Secondly, what will happen as if the vlmax > 2^sew?
for example:
if VLEN=512, SEW=8 and LMUL=8
the vlmax will be 512, and need 9 bit to represent the element index.

**Comment by aswaterman** [comment]
`vid` is useful when the computation is a function of the index (something that happens more often in OpenCL or element-function programming models).

When vlmax > 2^sew, the instruction follows the same discipline as `iota`: the instruction is legal, and the results are taken modulo 2^sew.  I will update the spec to include this fact.
