### ISSUE TITLE
Segment load/store - wraparound ?

### ISSUE THREAD

**Issue by eroom1966** [riscv/riscv-v-spec#188]
Please could you indicate the intended behavior for segment load/store instructions when the target registers would "wrap round" the register bank? For example, for instruction 
    vlseg8b.v v29, (a0)
does the instruction:

1. update registers v29, v30, v31, v0, v1, v2, v3, v4; or
2. cause an illegal instruction exception; or
3. something else?

Thx
Lee

**Comment by kasanovic** [comment]
Decided this would be Illegal instruction, to provide forward compatibility with longer encoding that has more addressable vector registers.
