### ISSUE TITLE
round calculation for single-width scaling shift

### ISSUE THREAD

**Issue by chihminchao** [riscv/riscv-v-spec#194]
Based on [13.5](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#135-vector-single-width-scaling-shift-instructions),
"# For vxrm=rnu, round = 1 << (src2-1)" 
Is  it a typo?  I think it should be 
""# For vxrm=rnu, round = 1 << (sew-1)"

**Comment by kasanovic** [comment]
qThe abbreviated expression is correct, the round bit is shifted up by one less than the value in the second source operand (v[vs1], x[rs1], imm), not sew-1.
