### ISSUE TITLE
inconsistent vmv.v.? definition

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#198]
Before today (Fri May 31), we had "pseudoinstruction vmv.v.v vd, vs1", now we have "vmv.v.v vd, v0, vs1 # vd[i] = vs1[i]".  The extra v0 operand in the middle appears to be an editing error, as it doesn't make much sense to have a 3 operand move instruction.  Also, the similar vfmv.v.f only takes two arguments, and has an implicit v0 as vs2.

If we drop the middle operand, then the second paragraph above needs to be edited, as it talks about the first and second source operands.  It probably should be edited to look more like the vfmv description, except the bit about splatting the operand.  There is also "instructions copies" here which should be "instruction copies".  Also, the first paragraph above now seems to be superfluous, as this is no longer a special form of vmerge but rather a separate vmv instruction.

If we keep the middle operand, then the paragraph below needs to be fixed to add the missing operand to the vmv.v.i instruction, and there is also one in the vector-examples.adoc file that needs to be fixed.

**Comment by kasanovic** [comment]
This was an editing error.
