### ISSUE TITLE
shift range for single-width scaling shift

### ISSUE THREAD

**Issue by chihminchao** [riscv/riscv-v-spec#201]
Base on [13.5](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#135-vector-single-width-scaling-shift-instructions)

The allowed shift amount describes 
"The low lg2(2*SEW) bits of the vector or scalar shift amount value are used (e.g., the low 6 bits for a SEW=64-bit to SEW=32-bit narrowing operation). "

But vssrl/vssra are not narrow instructions and vs2 is single-width (SEW) operand here and.  Should it be  lg(SEW) bits ?

**Comment by kasanovic** [comment]
This was a typo.  Fixing in next commit.
