### ISSUE TITLE
Can stride be negative number in Vector Strided Instructions ?

### ISSUE THREAD

**Issue by wwang0** [riscv/riscv-v-spec#203]
I see no clear declaration about if the byte stride can be negative number(signed) or not. We need clarification.

**Comment by aswaterman** [comment]
There's already a note about this: "Note: Negative and zero strides are supported."

**Comment by aswaterman** [comment]
I realized the note only applied to segmented strided ones.  Fixed to apply to non-segmented ones.

**Comment by wwang0** [comment]
I see the note only under "Vector Strided Segment Loads and Stores" session, should't we move it under Vector Strided Instructions?

**Comment by wwang0** [comment]
Yes:)
