### ISSUE TITLE
Runtime detect ELEN length

### ISSUE THREAD

**Issue by rednoah91** [riscv/riscv-v-spec#209]
My scenario codes is:
```
vsetvli vl, t0, e32, m1
vmv.v.x v_zero, x0
vwredsum.vs v_acc, v_x_mul, v_zero
```
This is work at ELEN=64 machine but get exception at ELEN=32 machine

So as title, do we have method to detect ELEN length at runtime?
Or do you have other suggestion to deal with this scenario : )?

Thanks

**Comment by kasanovic** [comment]
This is just one example of trying to use an unsupported instruction or configuration.

Normally, code would be compiled for a given machine knowing ELEN.

ELEN can be determined at runtime by writing to vsew using vsetvli and seeing if the value in vtype is legal.
