### ISSUE TITLE
Could we have option to disable rounding?

### ISSUE THREAD

**Issue by rednoah91** [riscv/riscv-v-spec#211]
My scenario is to right-shift a immediate value and saturate to 16-bit
I use ` vnclip.vi vd, vs2, 0x9 ` (vd[i] = clip(round(vs2[i] + rnd) >> vs1[i]))
The rounding mode will round SEW bits, which function I don't need.

I think it may be flexible to have an option to enable/disable rounding.
How do you think : )?

**Comment by kasanovic** [comment]
vxrm has rounding mode setting.
Setting vxrm=10 gives "truncate" which is same as no rounding.
