### ISSUE TITLE
vs1 field in encoding of vmpopc, vmfirst

### ISSUE THREAD

**Issue by rkruppe** [riscv/riscv-v-spec#213]
vmpopc and vmfirst are unary operations encoded as regular OPMVV instructions instead of under VMUNARY0, so they have an unused vs1 field which the spec doesn't seem to talk about at all. I would expect that it must be set to zeros and other bit patterns are reserved (cf. vs2 in vid), but whatever is intended, it needs to be written down.

(Alternatively, is there a reason why these aren't under VMUNARY0? That would also solve this issue.)

**Comment by aswaterman** [comment]
They should definitely be under VMUNARY0 to free up two opcodes.
