### ISSUE TITLE
Should we add retriction about dest/src register overlap for Integer/float Comparison Instructions ?

### ISSUE THREAD

**Issue by wwang0** [riscv/riscv-v-spec#215]
As the title, for example LMUL=2:
vmseq.vv v3, v2, vs4
It has WAR hazards without vector register renaming, and we should raise an illegal instruction exception for such case.

**Comment by aswaterman** [comment]
The answer should be the same for `vmadc` and `vmseq`.  The text for `vmadc` says, "an illegal instruction exception is raised if the destination vector register overlaps a source vector register group."  (This is stricter than necessary, as there's no WAR hazard when LMUL=1.)

I think we could relax the constraint on `vmadc` to exclude LMUL=1, and apply the same rule to `vmseq`.

**Comment by wwang0** [comment]
Agreed.

**Comment by aswaterman** [comment]
I did consider that possibility @wwang0, but it adds extra decode logic and probably doesn't help much in practice.

**Comment by wwang0** [comment]
That is ok. thanks
