### ISSUE TITLE
RISC-V assembly syntax vs 694-1985 - IEEE Standard for Microprocessor Assembly Language

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-v-spec#230]
It would be useful to consider the old attempt to standardize the assembler.
Many different assembler syntaxes from different corporations show that the standard was never been used in practice :-)

From the [694-1985 - IEEE Standard for Microprocessor Assembly Language](https://ieeexplore.ieee.org/document/29141) [DOI: 10.1145/800088.802820](http://doi.acm.org/10.1145/800088.802820), ISBN: 978-0-89791-024-8, Google-Books-ID: dh5IxAEACAAJ:

> 4.1.1 Instruction names. The naming of instructions shell be in accordance with the following rule:
>
> Instruction names shell begin with an action verb.

> 4.1.2 Instruction mnemonics. The selection of mnemonics fo instructions not contained in this standard shell be in accordance with the following rules (exceptions are noted herein):
>  a) The first character of the mnemonic shall be the first letter of the action verb.
>  b) Addressing modes shall not be embedded in the mnemonic.
>  c) Operand designations shell not be embedded in the mnemonic.
>  d) Conditions shell be embedded in the mnemonic.
>  e) Operand type may be indicated, where appropriate, by the last character of the mnemonic, as shown below (the default operand type is word):

From the point of view of above standard (incomplete list, for illustration only):

- `add  vd,vs1,vs2` instead `vadd vd,vs1,vs2` (`vd`/`vs1`/`vs2` are vector registers)
- mask is a condition, not a dummy operand - include it to mnemonic
  - `add.m  vd,vs1,vs2` instead `vadd vd,vs1,vs2,v0.t`
- `vl[bhwe]u?` unit-stride/strided/indexed are not the different instructions but addressing modes only
  - `lb.m   vd, (rs1)`     is the `vlb.v  vd, (rs1), v0.t` (`b` + mask condition is the suffix, `vd` is the vector register)
  - `lbu   vd, (rs1), rs2` is the `vlsbu.v  vd, (rs1), rs2` (`vd` is vector register, rs2 - is the x-register stride)
  - `lbu   vd, (rs1), vs2` is the `vlxbu.v vd, (rs1), vs2` (`vd` is vector register, vs2 - is the RVV-register offsets)
- vector-vector/vector-scalar/vector-immediate are not the different instructions but addressing modes only (note: The traditional order of the operands is used instead of the partially inverse order).
  - `op[.m] vd, vs1, vs2` instead of `vop.vv  vd, vs2, vs1,vm` (all operands are vectors)
  - `op[.m] vd, vs1, rs2` instead of `vop.vx  vd, vs2, rs1, vm` (rs2 is x or FPU register)
  - `op[.m] vd, vs1, imm` instead of `vop.vi  vd, vs2, imm, vm` (imm is numeric literal but not register)
  - `opf[.m] vd, vs1, vs2` instead of `vfop.vv  vd, vs2, vs1, vm` (all operands are vectors, `f.m` is mnemonic suffix)
  - `op[.m] vd, vs1, fs2` instead of `vfop.vv  vd, vs2, vs1, vm` (fs2 is the FPU register, `.m` is mnemonic suffix)
- `sub vd, rs1, vs2` instead of `vrsub.vx vd, vs2, rs1`
- `sub  vd, vs1, rs2` instead of `vsub.vx vd, vs2, rs1`

Of course, to distinguish the names of registers from other identifiers it would be good to use, for example, the prefix "%" before register name.

**Comment by kasanovic** [comment]
Why is this useful?  The standard itself was withdrawn.  How many assemblers followed the standard when it was active?

Mask is not just a dummy operand but will be a full register in longer encoding.
