### ISSUE TITLE
Vstart saved when interrupt happens 

### ISSUE THREAD

**Issue by fuyao-wong** [riscv/riscv-v-spec#237]
when VLEN = 256b,SLEN = 128b,SEW = 32, LMUL=4, so four vector registers hold elements as shown:
byte     1f          1c          18            14             10                  c               8              4             0
v4*n                  13          12            11             10                 3               2              1             0
v4*n+1              17          16            15             14                 7               6              5             4   
v4*n+2              1b          1a            19             18                 b               a              9             8 
v4*n+3              1f           1e            1d             1c                  f               e              d             c
there are two group in vector registers. data in same register will be executed at same time, but elements belong to different group.
when interrupt happens, what value should be set in Vstart ?  index 4, or index 14?

**Comment by aswaterman** [comment]
vstart contains an element index in the register group.  So for most instructions, vstart can be in the range [0, (LMUL * VLEN / SEW) - 1].
