### ISSUE TITLE
listing.adoc: invalid signatures of `imm` variants

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-v-spec#25]
https://github.com/riscv/riscv-v-spec/blob/master/listing.adoc
See `vaddi`, `vsubi`, etc
`vs2` are in signature instead `imm`

**Comment by colinschmidt** [comment]
Listing.adoc is intended to be updated and then merged with the v-spec.adoc.

Pull requests to help this process along are appreciated.

**Comment by aka-sps** [comment]
Sorry, it is difficult for me in mobile version of browser.
