### ISSUE TITLE
What is the effective SEW when considering EDIV and widening?

### ISSUE THREAD

**Issue by lihanglin** [riscv/riscv-v-spec#251]
Suppose there is a hardware which supports the maximum configuration like SEW=32b, FLEN=32b, EDIV=8.

there is a sentence mentioned in the chapter 14. Vector Floating-Point Instructions

>If the current SEW does not correspond to a supported IEEE floating-point type, an illegal instruction exception is raised.

I have a question about **the current SEW**?  Would it be the effective SEW?

A code sequence like below
```asm
vsetvli x0, x0, e64, m1, d4
vfwadd.vv v3, v2, v1  # Widening FP add
```
the effective SEW for vfwadd would be 64*2/4 = 32 and treat it as a legal instruction?
and this case
```asm
vsetvli x0, x0, e32, m1, d2
vfwadd.vv v3, v2, v1  # Widening FP add
```
the effective SEW should be 32*2/2 = 32 and still a legal instruction?

**Comment by kasanovic** [comment]
Yes, that's the intent.
EDIV is an optional extension that will need more work in definition.
