### ISSUE TITLE
What is the value of VM bit encoding for mask-register logical instructions?

### ISSUE THREAD

**Issue by lihanglin** [riscv/riscv-v-spec#252]
Not only the instructions in chapter 16.1 but also 17.6 (vcompress.vm) did not support masking.
The spec. did not specify what the VM bit exactly is for those instructions.
Was it treated as Don't Care or Should be One/Zero?

**Comment by jim-wilson** [comment]
Unmasked instructions are always VM=1, but the docs could perhaps explicitly say that like it does for a few others.  When an instruction doesn't support masking, VM=0 should be a reserved encoding.  The docs do say this for a few instructions.  This could probably be improved to be more consistent across all instructions that don't support masking.

**Comment by lihanglin** [comment]
@jim-wilson 
Agree with you
