### ISSUE TITLE
Will exception be raised when vl = 0 ?

### ISSUE THREAD

**Issue by wwang0** [riscv/riscv-v-spec#253]
Suppose vl = 0, and the memory address of a vector load instruction is illegal, will exception be raised? or no exception?

**Comment by aswaterman** [comment]
Only active elements can cause exceptions (https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#54-prestart-active-inactive-body-and-tail-element-definitions), and when vl=0, no elements are active.

**Comment by wwang0** [comment]
Got it.
