### ISSUE TITLE
signed or unsigned shift for vaadd and vasub

### ISSUE THREAD

**Issue by jovireal** [riscv/riscv-v-spec#256]
For vaadd and vasub, should the sum be treated as signed data or unsigned data before right shift? It may produce different result.

**Comment by jovireal** [comment]
For example, if the result is 0xff, it means -1 in signed data and maximum value in unsigned data，and the >>1 bit operation should be clarified. Or the default setting is signed data?

**Comment by aswaterman** [comment]
It's actually not about the signedness of the shift; it's about the signedness of the addition.  But your point stands.  For 8-bit numbers, the unsigned average of 0 and 0x80 is 0x40, whereas the signed average of 0 and 0x80 is 0xc0.

I assume given the lack of a `u` suffix that these are signed instructions, but I wonder if the omission of the unsigned variants is deliberate.

**Comment by kasanovic** [comment]
These were intended to be signed.  Adding unsigned variants might be justified.

**Comment by kasanovic** [comment]
Task group agreed to add both signed and unsigned variants.
