### ISSUE TITLE
Misleading order rule in the code comment for "vfwredocum.vs" instruction

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-v-spec#258]
The code comment for "vfwredocum.vs" instruction in section 15.4 states that:

                    `# Ordered reduce 2*SEW =  2*SEW + sum(promote(SEW))`

It makes people think that the ordered rule for this instruction is to sum all of the vs2 elements first and then add the vs1[0] element last.

However, the following description says that "The reduction of the SEW-width elements is performed as in the single-width reduction case, with the elements in vs2 promoted to 2*SEW bits before adding to the 2*SEW-bit accumulator."

And in the single-width ordered reduction sum case in the previous section (15.3), the ordered rule is described as `(((vs1[0] + vs2[0]) + vs2[1]) + …​) vs2[vl-1]`, i.e., vs1[0] is added to vs2[0] first.

If the ordered rule for "vfwredosum.vs" is the same as "vfredosum.vs", then the code comment needs to be modified or clarified to clear the misleading idea of adding vs1[0] last.

**Comment by aswaterman** [comment]
The comment is misleading.  The intent is "performed as in the single-width reduction case".  I'll fix the comment to match the single-width case.
