### ISSUE TITLE
When vl <=OFFSET < VLMAX, does tail element need to be set 0 for vslideup? 

### ISSUE THREAD

**Issue by wwang0** [riscv/riscv-v-spec#263]
As the title. No valid element is changed, do we still need to zero the tail elements?

And can I assume if No valid element(before vl) is changed, tail elements don't need to be zero'd ? an extreme case is vm masks all(no active elements), do we need zero tail elements per our current policy. Thanks

**Comment by aswaterman** [comment]
No. Tail zeroing depends only on vl and vstart. It does not depend on the
mask settings (as that would significantly complicate some implementations).

**Comment by wwang0** [comment]
OK. How about my first question:
"
When vl <=OFFSET < VLMAX, does tail element need to be set 0 for vslideup?
"
Thanks

**Comment by wwang0** [comment]
When vl <= OFFSET < VLMAX, and vl > vstart, we need zero the tail element, and then you will find only tail elements are updated. Is that desired?

**Comment by aswaterman** [comment]
When vstart < vl, elements past vl are always zeroed.  These instructions are not unique in that respect.

**Comment by wwang0** [comment]
Thanks. So close it.
