### ISSUE TITLE
vm mask on vslide* instructions

### ISSUE THREAD

**Issue by wwang0** [riscv/riscv-v-spec#267]
Does the vm mask work against the source register or the destination register in vslide* instructions?

**Comment by aswaterman** [comment]
The same rule applies as for other masked instruction: it affects which
destination elements are written.

**Comment by wwang0** [comment]
Then I think  the constraints on all vslide* overlapping the mask register can be relaxed: dest register can overlap with mask register when LMUL = 1.

**Comment by aswaterman** [comment]
I don't think that would work for vslideup or vslide1up, for the same reason overlap is disallowed on the vs2 argument: you'd destroy part of the mask before you got to use it.

We already have relaxed this constraint for vslidedown (3f117c435d9fc07a6ca43c3d08abb75a1f43cf1f) but it looks like we forgot to make the same change for vslide1down.  I will fix that.

**Comment by wwang0** [comment]
@aswaterman ， but mask is just against destimation elements, how can it be destroyed for vslideup/vslide1up?

**Comment by aswaterman** [comment]
Hmm, you're right.  I think that overlapping the mask register could be allowed when LMUL=1.  I'll make the pull request.

**Comment by wwang0** [comment]
Great!
