### ISSUE TITLE
Inconsistency in "Vector Widening Saturating Scaled Multiply-Add" examples

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-v-spec#270]
In chapter 13.4 Vector Widening Saturating Scaled Multiply-Add, there are the code examples as follows:

```
# Widening signed-unsigned-integer scaled multiply-accumulate
vwsmaccsu.vv vd, vs1, vs2, vm
             # vd[i] = clip(-((signed(vs1[i])*unsigned(vs2[i])+round)>>SEW/2)+vd[i])
vwsmaccsu.vx vd, rs1, vs2, vm
             # vd[i] = clip(-((signed(x[rs1])*unsigned(vs2[i])+round)>>SEW/2)+vd[i])

# Widening unsigned-signed-integer scaled  multiply-accumulate
vwsmaccus.vx vd, rs1, vs2, vm
             # vd[i] = clip(-((unsigned(x[rs1])*signed(vs2[i])+round)>>SEW/2)+vd[i])
```

The code comment says "multiply-accumulate" and the instruction mnemonic is "macc", but the operation equation has "minus" sign in front of the multiplication result. Should the "minus" sign be removed?

**Comment by aswaterman** [comment]
This is an editing error that arose when the multiply-subtract instructions were replaced with signed-unsigned multiply-add instructions.  Thank you for finding it.
