### ISSUE TITLE
Instruction syntax of vmsleu.vi and vmsgtu.vi

### ISSUE THREAD

**Issue by lihanglin** [riscv/riscv-v-spec#275]
Both instructions are integer comparison, unsigned

> vmsleu.vi vd, vs2, imm, vm
 vmsgtu.vi vd, vs2, imm, vm

The immediate operand is unsigned and the syntax would be

> vmsleu.vi vd, vs2, **uimm**, vm
vmsgtu.vi vd, vs2, **uimm**, vm

correct?

**Comment by jim-wilson** [comment]
Immediates are always signed, except for shifts and shift-like instructions like the slide and saturation instructions which truncate the immediate for the shift.

**Comment by aswaterman** [comment]
No. The immediate is sign-extended even for unsigned comparisons, just like
in the base RV32I.

**Comment by aswaterman** [comment]
Looks like Jim already responded but my email client hasn’t caught up yet.

**Comment by lihanglin** [comment]
Clear
Thank you all.
