### ISSUE TITLE
When vl=0, will scalar (non-vector) destination register be updated?

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-v-spec#284]
In section 3.3, a note states that

> As a consequence, when vl=0, no elements are updated in the destination vector
> register group, regardless of vstart.

This only talks about destination vector registers. What is the correct behavior if the destination register is a scalar (non-vector) register? For example, vmv.x.s, vfmv.f.s, vpopc.m, vfirst.m instructions?

**Comment by aswaterman** [comment]
By being silent on the matter, the spec implies that the scalar destination register is always written.  We should add a note to that effect (but there's no need for additional normative text).

This definition simplifies designs with scalar register renaming, and seems to be neutral for designs without.

The value written is unambiguous: vmv.x.s and vfmv.f.s copy element 0 (regardless of vl), and for the mask ops, there are no active elements, so e.g. vfirst.m returns -1 and vpopc.m returns 0.

**Comment by chuanhua** [comment]
It would be great if you could add such notes at the locations where each such instruction is being described. Thanks!
