### ISSUE TITLE
Unclear constraint when setting vl

### ISSUE THREAD

**Issue by rofirrim** [riscv/riscv-v-spec#286]
Hi,

the current section <q>6.2. Constraints on Setting vl</q> has 4 constraints and a 5th item with a summary of properties derived from those 4 constraints. 

In particular <q>5.c</q> says `vl ≤ VLMAX`. However this might not be true because constraint 2 only says `vl ≥ ceil(AVL / 2) if AVL < (2 * VLMAX)`.

This does not seem enough, and it looks to me we should explicitly state here that `vl ≥ ceil(AVL / 2) and vl ≤ VLMAX if AVL < (2 * VLMAX)` (or a slightly better formulation like `ceil(AVL / 2) ≤ vl ≤ VLMAX if AVL < (2 * VLMAX)`).

For instance, if `VLMAX=64` and `AVL=65`, then `vl` must be larger than 33 but nothing seems to prevent, from the constraints, that `vl` could be set to, say, 75. It should be obvious that `vl` can't be set to 75 in this case but this is not a property that follows from the 4 constraints.

Kind regards,

**Comment by aswaterman** [comment]
There is probably other text in the chapter that normatively constrains vl <= VLMAX, but even if that's the case, I think your suggestion makes the description clearer.
