### ISSUE TITLE
Widening left shift

### ISSUE THREAD

**Issue by jnk0le** [riscv/riscv-v-spec#289]
Current spec is missing widening left shift instruction from symmetry with narrowing right shifts.
It can be substituted with dummy widening addition followed by shift or widening multiply. But both cases require more instructions/latency and multipliers may be expensive as well.

**Comment by kasanovic** [comment]
Instruction added.

**Comment by kasanovic** [comment]
And instruction was deleted after task group discussion, after it was felt is was not important enough to justify as single instruction.
Widening multiply can substitute with single vector instruction (plus setting up scale amount), and widen+shift in other cases.  Providing all sign-extension cases would have expanded opcode footprint substantially.

**Comment by aswaterman** [comment]
Thank you—this would have been an irregularity in the implementation I’m working on.
