### ISSUE TITLE
how to determine which elements set fflags?

### ISSUE THREAD

**Issue by HanKuanChen** [riscv/riscv-v-spec#292]
According to [Vector Floating-Point Exception Flags](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#141-vector-floating-point-exception-flags), `fflags` will be set if any active element causes exception. That means a vector instruction may set all `fflags`.

Then how does programmers know which elements contribute to the flags?

**Comment by aswaterman** [comment]
The intuition behind this design is that most code checks the flags at specific points, not after every operation.  This is doubly true for RISC-V, which does not trap when floating-point instructions set the exception flags.

In some cases, and only when exceptions are rare, it's possible to speculatively vectorize the code, then re-run the problematic portion in scalar code to determine which element was at fault.

**Comment by HanKuanChen** [comment]
Thanks.
