### ISSUE TITLE
slide1up & slide1down illegal instruction exception

### ISSUE THREAD

**Issue by jeremyccl** [riscv/riscv-v-spec#293]
Hi 

Just wondering the condition of illegal instruction for slide1up & slide1down.
For slide1up, the destination register group can not overlap both vector mask register and source register group but slide1down only constraint not overlap vector mask register.

Any reason for these two instructions having different illegal instruction abort condition?

Thanks

**Comment by wwang0** [comment]
Take slide1up for example, suppose v1 is used as vd and vs2,  the first element of vs2 will become the second elelment of vd first, so here:
v1[1] = v1[0],
Next it will be v1[2] = v1[1], but v1[1] could be already modified by the first step. So it has potential read-after-write hazard in some implementation.
But slidedown doesn't have such hazard, so the destination regist er of slidedown can overlay with the source register.

As for mask register overlapping, it is already be relaxed in latest doc, and now destination register can overlap with mask register when VLMUL=1 both for slidedown and slideup.
