### ISSUE TITLE
vwmacc & vwmul signed & unsigned syntax 

### ISSUE THREAD

**Issue by jeremyccl** [riscv/riscv-v-spec#296]
vwmaccsu means vs1 is signed & vs2 is unsigned.
however vwmulsu means vs2 is signed & vs1 is unsigned.
why these two syntax expression for resource signed & unsigned are different?

**Comment by aswaterman** [comment]
See https://github.com/riscv/riscv-v-spec/pull/295

**Comment by kasanovic** [comment]
PR fixes this issue
