### ISSUE TITLE
vector compare instruction overlap constraint

### ISSUE THREAD

**Issue by jeremyccl** [riscv/riscv-v-spec#298]
In current spec, resource & destination group overlap constraint is not applied to vector mask compare instruction. 
But when vmseq.vv v11, v10, v2 and lmul >1, v11 may be updated before vs2 read.
Why this overlap constraint is not applied to vector compare instruction ?

**Comment by JamesKenneyImperas** [comment]
The last statement in section 12.7 is:

_For all comparison instructions, an illegal instruction exception is raised if the destination vector register overlaps a source vector register group and LMUL > 1._

So I think this constraint is applied.
