### ISSUE TITLE
Typo in example of ANDed conditionals?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-v-spec#3]
The subsection "Vector integer arithmetic instructions" has this example:
> These conditionals effectively AND in the mask when producing 0/1 in output, e.g,
>```
> # (a < b) && (b < c) in two instructions
> vslt    v1, va, vb
> vslt    v1, vb, vc, v1
>```

Presumably the assembly syntax requires that the second VSLT instruction be written thus?:
```
 vslt    v1, vb, vc, v1.t
```

**Comment by brucehoult** [comment]
The current spec is already corrected. This should be closed.
