### ISSUE TITLE
There are two different syntaxes for mask register.

### ISSUE THREAD

**Issue by JerryShih** [riscv/riscv-v-spec#301]
@aswaterman 
Why we have two different usage for mask?
Here are the example:
1) vfsgnjn.vf vd, vs2, rs1, **v0.t**
2) vmerge.vxm vd, vs2, rs1, **v0**

**Comment by rkruppe** [comment]
IIRC the rationale in the meeting where this was decided was:

- `v0.t` syntax should be reserved for when the mask controls writeback, i.e., destination elements are undisturbed where the mask has 0s
- For `vmerge`, the mask register is not used in that way, instead all destination elements (up to vl) are written unconditionally (just the elements written depend on the mask bits)

**Comment by rkruppe** [comment]
See also discussion in https://github.com/riscv/riscv-v-spec/issues/189

**Comment by aswaterman** [comment]
Sounds like a good explanation to me.

**Comment by JerryShih** [comment]
@rkruppe 
Thank you.
