### ISSUE TITLE
Missed Vector Widening Integer Multiply-Add Instructions?

### ISSUE THREAD

**Issue by JerryShih** [riscv/riscv-v-spec#310]
The rvv has:

> Integer multiply-sub, overwrite minuend
> vnmsac.vv vd, vs1, vs2, vm    # vd[i] = -(vs1[i] * vs2[i]) + vd[i]
> vnmsac.vx vd, rs1, vs2, vm    # vd[i] = -(x[rs1] * vs2[i]) + vd[i]

But why there is no correspond instruction in "Vector Widening Integer Multiply-Add Instructions"?
e.g.
There is no "vwnmsac".
If I try to do the similar thing as vnmsac, I need to use an additional instruction to generate the "-(vs1[i] * vs2[i])"

@aswaterman @kasanovic

**Comment by jim-wilson** [comment]
The negative multiply accumulate were dropped so we could add signed/unsigned variants.  See

commit b3bef9eef8d47143a0347e219844942d66ed91fd
Author: Krste Asanovic <krste@eecs.berkeley.edu>
Date:   Wed Jun 5 18:19:36 2019 -0700

    Replaced widening multiply-subtract instructions with widening signed/unsigned multiply-add instructions.

**Comment by JerryShih** [comment]
@jim-wilson 
Thank you, but I still can't know why.
If we try to have the result "vd[i] = -(vs1[i] * vs2[i]) + vd[i]", we should construct the "-vs1[i]" first.
That will need one more instruction. If we have vwnmsac, we could just call vwnmsac directly.

**Comment by jim-wilson** [comment]
There is a finite amount of instruction encoding space.  We don't have room to encode everything that everyone wants.  The decision was made to drop the two integer widening negative multiply accumulate instructions to make room for mixed signed/unsigned widening multiply accumulate instructions.  As you mentioned, you only need one more instruction to get an integer negative widening multiply accumulate, so there is very little gain from having those instructions.  But the mixed signed/unsigned widening multiply accumulate instructions added in their place can not easily be generated from other existing instructions, so these have more benefit.

**Comment by JerryShih** [comment]
Thank you.
