### ISSUE TITLE
vrgather typo?

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-v-spec#313]
The vrgather description has this:

vrgather.vx vd, vs2, rs1, vm # vd[i] = (x[rs1] >= VLMAX) ? 0 : vs2[rs1]

where I think it means:

vrgather.vx vd, vs2, rs1, vm # vd[i] = (x[rs1] >= VLMAX) ? 0 : vs2[x[rs1]]

**Comment by aswaterman** [comment]
Yep, thanks for pointing this out, Bill.
