### ISSUE TITLE
Best way to load/store a mask register?

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-v-spec#315]
Does here any better way to load / store a mask register without changing `vl` and `vtype`? 

```
li t0, -1
vsetvli x0, t0, e32 # Set VL to VLMAX
vle.v  v0, (t1) # Load masking to v0
```

Compiler need that operation to spill a mask register.

**Comment by aswaterman** [comment]
I think that’s it. Or, in prologue/epilogue code, you spill/fill it as part
of a larger block of registers (e.g. spill all of v0-v7).

On many machines, the extra vsetvli won’t matter too much, and spilling
mask registers shouldn’t be super common, so I think this is OK.
