### ISSUE TITLE
Add the float version of slidedown/up instructions.

### ISSUE THREAD

**Issue by JerryShih** [riscv/riscv-v-spec#318]
Ref: https://github.com/riscv/riscv-v-spec/issues/236#issuecomment-507997226

I had used the slidedown/up instructions in a loop, the are some extra costs for float-to-int conversion.
If there is no extra work to have the float version of slidedown/up, please make both float and int version of slidedown/up.

@aswaterman @kasanovic

**Comment by JerryShih** [comment]
Here is my use case.
I try to compute a serial of fp32 values, and push them into a vector register.
If the loop number becomes bigger, the cost of "fmv.x.s" will be a problem.

```
loop:
    .... // a complex formula for fp32_vlaue
    fmv.x.s int_value, fp32_value
    vslide1down.vx v0, v0, int_value
    ....
end_loop:
```

**Comment by kasanovic** [comment]
Irrespective of whether we add the float version, the code example given would generally run much faster and lower energy if you were to do scalar stores into a memory buffer, then do a single vector load to bring into vector register file.  Every vslide1down has to read and write the entire vector register VLMAX times, i.e., O(VLMAX^2) operands moved, whereas using a memory buffer only writes and reads each element once from RAM and once into a vector register, i.e., O(VLMAX) operands moved.

**Comment by kasanovic** [comment]
Asking TG opinion.

**Comment by David-Horner** [comment]
The most significant use case is when XLEN < FLEN.  (RV32 and D float).
The transfer to integer to vector register is not possible.

However, I would prefer scalar vslide1down.vs vslide1up.vs to vslide1down.vf
The float to scalar can be fused with the vslide1.

**Comment by JerryShih** [comment]
> Asking TG opinion.

@kasanovic 
Any update for float version of slidedown/up?

**Comment by aswaterman** [comment]
@JerryShih added.
