### ISSUE TITLE
Separate FP instructions from Base + "Overload" polymorphics onto remaining V instructions

### ISSUE THREAD

**Issue by xphung** [riscv/riscv-v-spec#32]
To take vbx-glemieux's idea (https://github.com/riscv/riscv-v-spec/issues/24) a bit further, I'd suggest:

1.  Separate FP instructions from Base Vector extension, eg. call this "Zvecfp"

2.  Map polymorphic Vector types extension instructions onto (remaining) V Base opcodes (only using new opcodes when there is no corresponding V Base instruction).  The behaviour of each overloaded opcode is then determined by the "vtypeen" bit, so there will be no confusion, e.g. if vtypeen=0 then VSUB opcode is plain integer vector subtraction, of if vtypeen=1 then VSUB becomes a polymorphic vector subtraction.... Let's call the polymorphic types extension "Zvectypes"

Then the possible implementations options are:
(a)  V (integer only)
(b)  V (integer only) + Zvecfp
(c)  V (integer only) + Zvectypes 
(d)  V (integer only) + Zvectypes + Zvecfp

What's interesting is that for options (a), (c) and (d), it's possible to write code that uses only the "polymorphic" instruction set (or it's overloaded integer instructions).  Who knows, in the very very very long term, we could possibly deprecate the "Zvecfp" instructions (with it's multiplicity of h/s/d/q forms), and thus the Vector extension will revert back to a cleaner, single set of polymorphic instructions.

**Comment by kasanovic** [comment]
It's agreed that what portions are mandatory in base V spec, and what additional standard extensions are specified, is still up for discussion. For now closing this issue, as we need to develop a concrete proposal for standard profile layers to assist software/compiler developers based on the new 0.6 spec.
