### ISSUE TITLE
Table 10. Vector AMO width encoding clarification

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#322]
The last line of table 10 specifies that "mem bits" for SEW-sized operations is 64. Is this correct? I would have expected it to be SEW instead.

**Comment by aswaterman** [comment]
Looks like it should be SEW.

**Comment by kasanovic** [comment]
64 was actually intended, as RV32/64 only support AMOs on W and D values.

But we could define 64b encoding as SEW, to support possible future atomic sizes, and to match other load/stores.

**Comment by kasanovic** [comment]
But looks like it was changed to SEW later... Moving to SEW.
