### ISSUE TITLE
Clarify vwred* and vfwred* instructions with LMUL=8

### ISSUE THREAD

**Issue by larryrong** [riscv/riscv-v-spec#323]
Hello,

I have a question about vwred* and vfwred* instructions with LMUL=8.

According sepc 

- ch5.2 says, 

```(1)The largest vector register group used by an instruction can not be greater than 8 vector registers, and if a vector instruction would require greater than 8 vector registers in a group, an illegal instruction exception is raised.```
```(2)attempting a widening operation with LMUL=8 will raise an illegal instruction exception```

- ch15.2 says,

```The unsigned vwredsumu.vs instruction zero-extends the SEW-wide vector elements before summing them, then adds the 2*SEW-width scalar element, and stores the result in a 2*SEW-width scalar element.```

According to spec ch5.2(1) and ch15.2, the number of vector register group of vwred* and vfwred* instruction was 8 and these instructions did not violate ch5.2(1) under widening reduction instruction with LMUL=8.

But ch5.2(2) says widening instruction with LMUL=8 will raise an illegal instruction exception.

What's correct? 

Thanks,
Larry

**Comment by kasanovic** [comment]
The 5.2 text should be clarified to only raise exceptions when a vector register group would need to be LMUL>8.  The scalar reduction in/out operand has an effective LMUL of 1.
