### ISSUE TITLE
vstart should not be visible from userspace

### ISSUE THREAD

**Issue by jnk0le** [riscv/riscv-v-spec#333]
As of cd0cc6c `vstart` is no longer a "nice but sometimes slow feature", so I think it is reasonable to leave it exclusive for interrupts/context switches.

The sentence:
> vstart should not be used by application programmers.

now means that, in worst case, we are about to see "standardization" of some particular implementations.

**Comment by aswaterman** [comment]
OTOH, making vstart privileged would interact poorly with user-level
interrupts, should that feature eventually become relevant.

**Comment by jnk0le** [comment]
The N extension adds enough CSRs to screw with, that vstart can be aliased similarly only when N extension is active.

**Comment by kasanovic** [comment]
Hiding vstart from unprivileged code would make it difficult to provide user-level threading libraries, even without N extension.  (I'll note SPARC had related issue with register window overflow/underflow).
