### ISSUE TITLE
Typo in example in 17.6. Whole Vector Register Move

### ISSUE THREAD

**Issue by lihanglin** [riscv/riscv-v-spec#345]
There is an example in 17.6 Whole Vector Register Move

> vmv4r.v v4, v8   #  Copy v4=v8; v5=v9; v6=v10; v7=v12

Should it be  ?

> vmv4r.v v4, v8   #  Copy v4=v8; v5=v9; v6=v10; **v7=v11**

**Comment by aswaterman** [comment]
Yeah, thanks for catching the typo.

**Comment by aswaterman** [comment]
Closed by 181f232439496fe7d3ab54672884512947379f22
