### ISSUE TITLE
vstart application to load/store including vlxff 

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-v-spec#359]
Zvlssegg extension explicitly mentions vstart as applicable to restarting at units of structures.
This implies that all the vector load/store instructions can resume with a vstart not equal to zero.
This should be stated explicit in the load/store section. I'm certainly willing to make a PR for it.

It raises the question whether vstart is applicable to the Fault-only-first load instructions.
Some faults are avoided because the vl is reduced to only process non-faulting elements. However, some faults cannot be avoided, especially interrupts. In this case it may be very advantageous to resume the load rather than process a truncated set of elements. (In particular the buffering of read elements may be lost during the processing of a memory heavy loop).

I propose vstart also be applicable to the Fault-only-first load instructions.
And it also be noted that on a trap vl should not be reduced. 
Again I'm willing to do the PR if this is what is intended.

**Comment by aswaterman** [comment]
The fault-only-first loads should be interruptible, which means they should be able to handle nonzero vstart.  (It's still the case that address exceptions will only happen on element 0, regardless of vstart.)
