### ISSUE TITLE
vfredsum should refine its choice of additive identity

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#385]
The current spec says that masked vfredsum instructions are permitted to substitute a +0 for a masked-off element, which simplifies some datapath designs.  That's still a fine idea, but to propagate signed zeros correctly, I think we should slightly refine the definition to preserve signed-zero behavior.  Instead of unconditionally using +0, we should use +0 when rounding towards -Inf, and -0 for all other rounding modes.  That way, if a partial sum is zero, adding in the identity element will preserve the partial sum's sign bit.

There shouldn't be any critical-path impact, and the HW cost is pretty trivial.

**Comment by kasanovic** [comment]
can you prepare a PR?
