### ISSUE TITLE
Inconsistent behavior for vfslide1up.vf/vfslide1down.vf when FLEN<SEW

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#409]
There is something that doesn't feel quite right in the definition of `vfslide1up.vf`/`vfslide1down.vf`. The statement:

- _If FLEN < SEW, the scalar value is NaN-boxed (one-extended) to SEW bits._

doesn't seem to fit with other features of floating point. In particular, section 14 says, with regard to floating point instructions:

- _If the current SEW does not correspond to a supported IEEE floating-point type, an illegal instruction exception is raised._

and:

- _Vector floating-point instructions require the presence of base scalar floating-point extensions corresponding to the supported vector floating-point element widths._

Since this is a floating point instruction, how can it be then that `FLEN` < `SEW`? Wouldn't that be an unsupported vector floating-point element width?

Note that `vfmerge.vfm` and `vfmv.v.f` only mention the case when `FLEN` > `SEW`, not `FLEN` < `SEW`.

I think the specification should revised to either:
1. Remove the `FLEN` < `SEW` reference from `vfslide1up.vf`/`vfslide1down.vf`; or
2. Add similar statements to other instructions with an f register source, and correct the statement regarding illegal instruction exceptions.

Andrew pointed out that the same text is present for `vfmv.f.s` and `vfmv.s.f` as well, so these should be included in the same review.

Two further notes to consider when discussing this:
1. For `vfmv.f.s`, when `SEW`=8 the current specification implies the `f` register result will be NaN-boxed from bit 8. Is this useful?
2. For `vfmv.s.f`, `vfslide1up.vf` and `vfslide1down.vf`, the current specification implies that when executed with `SEW`=64 on an implementation that only supports `FLEN`=32, the `v` register result will be NaN-boxed in bits 32-63. Since `FLEN`=64 is not supported in the vector extension on such an implementation (see extracts above), is this useful?

**Comment by kasanovic** [comment]
Factored out text into one place, and made clear that illegal instruction execution should be raised whenever a floating-point vector operand's EEW is not of a supported type (which subsumes above cases.)
