### ISSUE TITLE
Context save/restore between different cores

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-v-spec#41]
The context stored on one core cannot always be restored and executed on another core.

The capabilities of vector units even in one system may be different.
It is required to find a method to determine whether a certain context can be loaded onto another kernel or not.

While the supported sets of vector instructions may be defined via CSRs, the “MAXVL” values for same configuration may be different too.

**Comment by colinschmidt** [comment]
This is a platform/profile issue. It was mentioned in #42.
