### ISSUE TITLE
Place stabler RVV control fields in bits [30:12] of vtype.

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-v-spec#410]
Discussion had been ongoing to define an at least two bit field to handle various agnostic modes. #367
Raised but not discussed on the last call was the possibility of placing this agnostic state field in another csr.

The alternative to a different csr is that such configuration fields instead be established in bits [30:12] of vtype. Such configuration field values are expected to be of longer retention than say SEW or EDIV.

  As mentioned in #396 (reserve bits for custom use), bit 11 is particularly challenging to use appropriately When negative it especially complicates bit 12 management, but also all the higher bits. I therefore propose in conjunction with this recommendation we also reserve bit 11 (or make custom).  

The key idea is this:
**vsetvli leaves bits [30:12] unchanged. The 11 bits in the instruction only change bits {10:0] of vtype unless an invalid combination occurs in which case vill is set and bits {11:0] are cleared.** 

Vsetvl will operate as previously proposed, all XLEN bits of vtype can be written. Individual fields can be WARL or WLRL and unused WPRI with most having a default of zero to align with current behaviour.

I have some further proposals that are of the same stabler nature as the agnostic modes, and I believe they also would be well addressed as upper bits in vtype.

Down side to inclusion in vtype:
1) unusual behaviour of vsetvli. That boat has sailed. Leaving the upper bits untouched vs set to zero is possibly unexpected, but so is much of vsetvli functionality.
2) use of vsetvl requires to set up the integer register (a LUI and addi would suffice) but the RVI X register read can cause a delay in the decode pipe as the value is propagated to a potentially loosely coupled processor.

Downside to new csr.
1) more context to save on a switch.
2) either a new vsetvli2 with a 12 bit immediate, or an optimized version of CSRRWI (which only supports 5 bits) is required.
[variations on 2 are possible with multiple CSRRWi writing into the same alternate vtype]. but any of these are possible with stabler control field inclusion into vtype.

And perhaps this is what Krste was meaning: a new virtual CSR that reads/writes 5 bits into specific fields (one or more) in vtype.
In any case this should be a good start for the discussion on where and how to provide stabler RVV control/status fields.

**Comment by aswaterman** [comment]
Why not put things that shouldn't be affected by `vsetvli` in `vcsr`?

**Comment by jnk0le** [comment]
Leaving upper bits unchanged, results in extra necessary prologue or epilogue in each vector enabled function.

How about using this bit 11 for selecting whether we want to clear or preserve upper bits?

**Comment by David-Horner** [comment]
@jnk0le -I like the suggestion of bit 11 use that avoids its problematic nature. 
The value of bit 11 preserve/clear is highly dependent on whether these stabler settings are of high use across many algorithms/optimizations.
If the subset of all zero stabler fields is sufficiently popular or universally applicable then bit 11 clear has valuable application as a shorthand for it. We won't know until these stabler fields have  been finalized/stabilized. Bit 11 can certainly be reserved now and implemented as deferred optimization (v1.1 candidate?) However, planning now to make sane and optimal defaults for the zero cases will make the adoption of this optimization more likely, and more importantly useful. ( hacks in v1.2+ of bit 11 setting non-zero values is possible but ugly-ugly).  

If vtype is considered "caller saved" then the function only need assure it sets up all of vtype for its own use, which it needs to do in the general case for the lower bits.  The burden on caller is less, as with proposed system calling convention. 
I will be proposing stabler fields that could be used transparently by the function, so enhanced conventions could further avoid prologue code. As well Link Time Optimizers could ensure the high bits are compatible across function calls avoiding even the minimal prolog of a vsetvl preceded by integer constant load. 

@aswaterman 
I wasn't sure how to read "that shouldn't be affected by vsetvli".
On the face of it, it implies sign extended vsetvli. That in effect no stabler field (other than values all 1 or zeros) should be in vtype. So I deal with the idea of what shouldn't be affected by a sign extended vsetvli and thus why undisturbed is valuable.
Alternatively, as I may have misread it, "Allow only those fields that are appropriate for vsetvli and its primary function to set vl". This is relevant and I also discuss it below.

**I agree that appropriate location choice in vector csrs is very important.** 
I took your advice for CLSTR.

The idea I intended is that vsetvli **should not disturb settings that are valuable to preserve even though lower bits are changing.** It provides a common optimization of vsetvli usage.

**What should be a candidate for stabler fields in vtype and thus be used and set by vsetvl[i]?**

The "vfill" field I will propose (within days , I hope) will affect vl calculation so should be in vtype.
It appears to be a good candidate for stabler. Other as yet unimagined fields are possible that also affect vl.

As for only including in vtype the "parameters" that affect vl, that ship is prepared to leave port as ediv.
As with ediv the value in placing stabler field in vtype is the practicality of its use with SEW and the rest.
Thus the proposed agnostic setting field could be appropriate as a stabler field.

So, I anticipate there will be fields that do not change vl themselves but interoperate with existing fields in vtype and interoperate with new stabler fields that would be candidates for vtype stabler.

Thus the proposal that vsetvli leave upper bits undisturbed, as a first iteration. (@jnk0le's optimization pending)

**Comment by kasanovic** [comment]
I think the actual proposal here is to change vsetvli to not modify upper bits of vtype.
I strongly disagree.

Vsetvli should retain current meaning with current encoding.  Bit 11 of immediate being zero clears the upper bits of vtype (assuming there were any).   As @jnk0le  mentions, it must be simple to establish vector configuration with a single vsetvli in common cases.

We can later choose that bit11=1 means preserve upper bits, but if/until we define upper bits in vtype, there is no need. As mentioned earlier, we might instead choose to define vtype to be a 12-bit window into some other CSR, in which case bit 11 of vsetvli immediate is fully usable and those upper bits in the other CSR are not disturbed. Note vtype was designed to not be writable except via vsetvl{I}. 

This is not really essential to this proposal, but I disagree that agnostic bits are longer-lived/more-stable in general than other vsetvl bits. In particular, mask-agnostic setting can be very fine-grain, depending on length of basic-blocks in control-flow DAG.  Similarly, an inner loop might contain computation that is tail-agnostic mixed with a reduction that is not.

I'm closing this issue as current design already supports desired effects, and I'm trying to clean up issue list for 0.9.

**Comment by David-Horner** [comment]
Sounds OK to me - but I made a mistake in describing the length of the immediate. The field is only 11 bits long, The high order bit used to select between the immediate and register variants.
So bit10 would be the zero upper bit. And as you described bit10 as 1 could preserve: the functionality I wanted is available at the cost of a single bit.

The equivalent bits with another ("windowed") CSR would be 11 bits.
With the Version 0.9-draft-20200424 design, SEW and a physical register group multiplier fully determine vl.
In that I believe vlmul can be removed altogether #418, getting at least 2 of those (now) 3 bits back tips the balance in my thinking. Even with the one bit "expended" for selective clear/preserve means at least a 1 bit net gain.

There is still room in the I instruction format's 12 bit immediate field to allow a vsetvli2 that sets a different combination of fields, so all these in combination future proof the vtype/vsetvli adequately.

Thank you all for your consideration of the idea.
