### ISSUE TITLE
A question about vmul instruction

### ISSUE THREAD

**Issue by linkLiao** [riscv/riscv-v-spec#419]
In instruction "vmulhsu",  the vs2 is signed, and another is unsigned
In instruction "vwmaccsu", the vs2 is unsigned, and another is signed

Why is different between these two instruction in the same suffix "su"

**Comment by jim-wilson** [comment]
The operand orders are different for binary and ternary instructions.  In vmulhsu vs2 is the first source operand, in vwmaccsu vs2 is the second source operand.  But in both, in the assembly syntax, the signed operand comes before the unsigned operand, hence both are su.  The different syntax for ternary instructions is explained near the end of section 11.1 in a footnote.
