### ISSUE TITLE
number of bits implemented in vl

### ISSUE THREAD

**Issue by RaphaelKlink** [riscv/riscv-v-spec#422]
There are two definition for number of bits in vl.

The XLEN-bit-wide read-only vl CSR

and

The number of bits implemented in vl depends on the implementation’s maximum vector length of the smallest supported type. The smallest vector implementation, RV32IV, would need at least six bits in vl to hold the values 0-32 (with VLEN=32, LMUL=8 and SEW=8 results in VLMAX of 32). 

Does this mean vl is supposed to be implemented similar to vstart, where XLEN-bits are read but only the necessary bits are changed by vsetvl?

**Comment by David-Horner** [comment]
Yes.
similar to vstart, where XLEN-bits are read but only the necessary bits are changed by vsetvl.
This is implicit in the description as the XLEN-bit-wide read-only vl CSR.
It is the same for all csr , that a read writes to all the bits of the rd register
