### ISSUE TITLE
What is the case when vsetvl is used, but vill is set in rs2 and other fields is non-zero?

### ISSUE THREAD

**Issue by HanKuanChen** [riscv/riscv-v-spec#428]
For `vsetvl rd, rs1, rs2 # rd = new vl, rs1 = AVL, rs2 = new vtype value`
What would happend if a user set `vill` in `rs2`, but also make `vlmul`, `vsew` and `vediv` non-zero?
Would new `vtype` just copy `rs2`?
or new `vtype` take `vill` and set `vlmul`, `vsew` and `vediv` zero?

**Comment by aswaterman** [comment]
"When the vill bit is set, the other XLEN-1 bits in vtype shall be zero" - so the second option.
