### ISSUE TITLE
Source Vector Operand Clarification of Instruction vfirst.m

### ISSUE THREAD

**Issue by daweili1226** [riscv/riscv-v-spec#430]
```
vfirst.m rd, vs2, vm
```

The vfirst instruction finds the lowest-numbered active element of the source mask vector that has its LSB set and writes that element’s index to a GPR. If no element has an LSB set, -1 is written to the GPR.

The `vfirst` instruction description does not mention `vs2` operand, can someone clarify the functionality and behavior of vs2 please?

**Comment by aswaterman** [comment]
`vs2` is the source mask vector that the description refers to.  (`vm` is the usual optional `v0.t` mask register.)
