### ISSUE TITLE
vtype, vsetvl[i] and backwards-compatibility

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#432]
I'm still digesting the fractional LMUL changes, but I wonder whether the proposed changes to `vtype` (and therefore `vsetvl[i]`) should be reconsidered. The proposed change makes all existing tool chains incompatible with the latest specification because fields have been moved and resized. If the indication for fractional LMUL was instead moved to bit 7, with all other fields kept in their previous locations, then existing tool chains would still work.

**Comment by aswaterman** [comment]
I also think we should consider this option. Depending on the nature of the other backwards incompatible changes, this could make a material difference on how much effort it takes to migrate to v0.9.

**Comment by David-Horner** [comment]
It becomes moot with #418  - vlmul goes away.
