### ISSUE TITLE
vlast.m Support 

### ISSUE THREAD

**Issue by daweili1226** [riscv/riscv-v-spec#433]
The following loop lives-out "c" variable, and now that we have vfirst.m to find the first lane set, why don't we have vlast.m to find the last lane set for this case? Here "c" expect the last lane because only the newest update is valid.
```
    for (int i = 0; i < num; i++) {
        if (a[i] == b) {
            c = a[i];
        }
    }
```

**Comment by aswaterman** [comment]
Duplicate of #389; please continue discussion there.
