### ISSUE TITLE
vsetvl, vsetvli and reserved vlmul (100)

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#441]
I assume that to avoid data-dependent traps, specifying the reserved value `100` for `vlmul` using `rs2` of the `vsetvl` instruction will set `vtype.vill` - is that correct?

What happens if the encoding specifying this reserved value is used for `vsetvli`? Is this an Illegal Instruction or does it set `vtype.vill`?

**Comment by kasanovic** [comment]
I feel the spec is already very clear on this in section 6.1:

> If the vtype setting is not supported by the implementation, then the vill bit is set in vtype, the remaining bits in vtype are set to zero, and the vl register is also set to zero.
