### ISSUE TITLE
how to do content switch on vtype CSR

### ISSUE THREAD

**Issue by jeremyccl** [riscv/riscv-v-spec#463]
Current RVV defines vtype CSR as RO. 
For RTOS doing content switch, the only way I know is to read vtype CSR and store it back by using setvl rd, rs1, rs2.
However, RTOS should not know AVL information, which is not stored in any CSR.
Is there any method defined by V extension to do content switch on vtype CSR?

**Comment by aswaterman** [comment]
Use the vsetvl instruction to restore the old context’s vl and vtype CSRs
at the same time. (And since vsetvl resets vstart, vstart needs to be
restored last.)

**Comment by jeremyccl** [comment]
Hi Andrew

As I know vl value depends on both AVL and vtype. If RTOS couldn’t get AVL from CSR or somewhere, how to make sure to restore old vl value by using setvl?

Thanks

**Comment by aswaterman** [comment]
You don't need the AVL; you just use the preserved value of the vl register as the AVL in the context-switch code.  The effect on architectural state is the same as if you actually used the AVL.

**Comment by jeremyccl** [comment]
I got it. Thanks.
