### ISSUE TITLE
How operations vmax.vv and vmax.vx are working?

### ISSUE THREAD

**Issue by MykolaMoshak** [riscv/riscv-v-spec#469]
Section 12.8 spec 0.8 describes max/min operations. I didn't get the point how it is exactly done.
E.g. for vmax.vv v1, v2, v3 would be v2 = [1, 2, 3], v3 = [3, 2, 1] => v1 = [3, 2, 3]. 
So, it performs elementwise max operation for both vectors and then saves the result into destination register v1, right? 

For vmax.vx would be: vmax.vx v1, v2, 0: v2 = [1, -1, 1] => v1 = [1, 0, 1]. Is it right?

Could someone explain how it exactly defined/works?  Thank you!

**Comment by aswaterman** [comment]
It's an element-wise operation, so it operates as you described.
