### ISSUE TITLE
ISA support to Managing implementation dependent characteristics

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-v-spec#476]
It was mentioned in the bi-weekly meeting that there are implementation dependent characteristics that prohibit the use of certain algorithms. This is in addition to how these characteristics affect inherent performance and directing ,if not dictating, preferred ways to optimize. Certain algorithms just cannot be implemented with specific  but legitimate design parameters.

As Krste said, SLEN<VLEN is just another configuration (some locked in by physical design) parameter that inhibits or prohibits software universality/portability. 

For years I have been grappling with how to 
1) determine and establish a profile for a given program, based on binary and/or source (including possible assembler/compiler directives) to determine the characteristics required by it.
2) provide a mechanism to validate that profile as a prolog to execution and
3) where such a prolog validation is not possible, that a run time exception is raised when the stated profile characteristics are exceeded
4) where it is not possible for the run time to determine that the characteristics are definitely exceed,  that an exception is conditionally raised when “exceeded is highly/most likely or even possible" on a stated configuration. (hopefully this provision is not necessary _-Ed_ )

It appears obvious to me that the exception mechanism 4) could be an optional feature as could 3.
But I believe the objective should be that 1 and 2 become part of the ISA standard, specifically the physical support required to validate the profile.

I raise this issue now because we are approaching 1.0 and have a better idea of RVV functionality and limitations.

I would appreciate working together with anyone that has an interest in this issue. Obviously the discussion and proceed here but I would also be open to brainstorming off line.

I understand that:
  RVI profiles have been proposed to address such issues. To date very little has been explicitly defined for such RVI profiles, even though, or perhaps because, many of the issues are already understood for other architectures. Further, the nature of the RVI application profiles is different than what I propose here. RVI profiles deal specifically with application domain, whereas the issue here is broader, also including interoperability within an application domain and  assurance of correct behaviour within an algorithm, rather than just performance/emulation/missing functionality.

Insight as to why RVI application profiles are indeed the same as the issue I raise here would be welcomed. Especially as that would lead to improvements in both RVI profile generation and adopting  mechanisms to deal with the issue for RVV.

**Comment by kasanovic** [comment]
This is not particularly an issue with current vector spec, and discussion can continue as email thread.  So closing this issue.
