### ISSUE TITLE
vsetvl[i] ta/tu and ma/mu flags

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#477]
Is it the intention that ta/tu and ma/mu flags to vsetvl[i] are optional? If so, are they assumed to be tu and mu if omitted?

(they are absent in all cases in the 0.9 example directory)

**Comment by kasanovic** [comment]
I think longer term, people would prefer them to be mandatory in assembly code.

In the interim, to reduce software churn, it is easier for current software developers/implementers if they're optional, with tu/mu being the default.

**Comment by JamesKenneyImperas** [comment]
Thanks. I think it would be useful to add your words above (especially the defaults) as a note in section 3.3.3, and perhaps to update the examples to use the preferred syntax.
