### ISSUE TITLE
vinsert masking options

### ISSUE THREAD

**Issue by go-sc** [riscv/riscv-v-spec#48]
Section 12.1:

> All vector masking options are available for `vinsert`.

I don't quite understand how exactly it should work. Can you put more details on that?

**Comment by a0u** [comment]
This follows the normal predication behavior, as with all other instructions.
For example, `vinsert vd, rs1, rs2, v0.t` would do:
`vd{rs2} = v0{rs2} ? rs1 : vd{rs2}`
