### ISSUE TITLE
vslideup overlap constraint

### ISSUE THREAD

**Issue by jeremyccl** [riscv/riscv-v-spec#480]
Hi

vslideup instruction has the constraint that source and destination vector register group cannot overlap even if LMUL = 1.
When debugger tries to fill scalar data into all 32 vector register files, the only way I know is use vslideup to move each scalar value. But one vector register can't be filled by vslideup under this constraint.
Is there any other method for debugger to write all 32 vector register?

**Comment by aswaterman** [comment]
vslidedown and vslide1down don't have this constraint, and there's a note addressing the debugging use case:

"The vslide1down instruction can be used to load values into a vector register without using memory and without disturbing other vector registers. This provides a path for debuggers to modify the contents of a vector register, albeit slowly, with multiple repeated vslide1down invocations."
