### ISSUE TITLE
What are the benefits of variable vector length compared to masks?

### ISSUE THREAD

**Issue by lemaitre** [riscv/riscv-v-spec#486]
Hello,

I know that vector extension uses `vsetvl` to change the effective size of vectors, and that is the mechanism used within loops to handle remaining elements at the end.

But this could also be implemented with fixed size vectors using masks.
This is, for example, the direction taken by SVE where there is no user instruction to change vector length.

I would think that having a global state that is often changed should be avoided.
Especially in this case where masks are already supported and are more versatile.

So I wonder: What are the benefits of `vsetvl` compared to setting some masks accordingly?

PS: This is a genuine question and not a way to ask to remove `vsetvl`

**Comment by kasanovic** [comment]
This is too long a discussion for a GitHub issue, and not really appropriate here, but using masks for vector-length control requires new mask control instructions that are morally equivalent to having vestvl.  You can view vl as separate mask register that is encoded and operated on more compactly than an expanded mask.
