### ISSUE TITLE
Implementations with minimum SEW>8

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#487]
We know of at least one group intending to implement the Vector Extension with a minimum supported SEW>8. This would seem to be largely compatible with the existing specification, with the exception of whole-register instructions, which are explicitly defined to _require_ an SEW of 8.

Perhaps the specification could allow more flexibility by allowing the minimum supported SEW to be a configuration parameter and define the whole-register operations in terms of that?

**Comment by kasanovic** [comment]
With the SLEN=VLEN decision, this issue will now be moot (though text needs updating).
