### ISSUE TITLE
why riscv-v-spec-0.9.html just list vle32 and vle64 instructions

### ISSUE THREAD

**Issue by luxufan** [riscv/riscv-v-spec#489]
in the riscv-v-spec-0.9.html, it just lists vle32.v and vle64.v instructions
<img width="1405" alt="截屏2020-05-28 下午10 03 05" src="https://user-images.githubusercontent.com/37958561/83151329-035a3600-a12f-11ea-8942-035d35938c61.png">
is there has some instructions like vle8.v vle128.v ...?

**Comment by jim-wilson** [comment]
If you look at section 7.2, you will see it is vle<EEW> and vse<EEW>.  These are just two examples of the instructions that exist.  The actual set of instructions depends on what the valid values are for EEW on the target.  For unit stride instructions, EEW is SEW, and values are defined for SEW up to 1028.  But listing vle1028.v would be potentially misleading, as most implementations probably won't support that.  An implementation is only required to implement loads and stores up to ELEN.

**Comment by kasanovic** [comment]
text can be expanded.

**Comment by kasanovic** [comment]
Fixed in update to 1.0-draft.
