### ISSUE TITLE
rvv-0.9 spec vlxseg indexed-unordered

### ISSUE THREAD

**Issue by luxufan** [riscv/riscv-v-spec#491]
how is the assemble representation of the vlxseg indexed-unordered instructions? vlxuseg3ei8?

**Comment by aswaterman** [comment]
Those instructions do not exist: "Only ordered indexed segment stores are provided. The segments must appear to be written in element order."

**Comment by luxufan** [comment]
emmm, is there unsigned segment load/store instruction?

**Comment by aswaterman** [comment]
The concept of signed/unsigned loads no longer exists in RVV 0.9, because loads always fill an entire element.

**Comment by kasanovic** [comment]
Closing this as there is no issue here now.
