### ISSUE TITLE
Tips&tricks for decoding of instructions

### ISSUE THREAD

**Issue by Marc43** [riscv/riscv-v-spec#494]
Hi,

I wanted to know if at the time you designed the specs you thought of some things that would be useful to know for someone that is trying to decode instructions.

To make it clearer, for example, if I want to classify widening instructions there may be common unique bytes in `funct6` or something like this. I think that this would make my life easier.

Thanks!!

**Comment by kasanovic** [comment]
The instruction table is laid out to help see the patterns.
