### ISSUE TITLE
vector load instructions

### ISSUE THREAD

**Issue by chenwei-tw** [riscv/riscv-v-spec#50]
Since the vector can be configured to `vsew` = 32-bit, we are able to have a quad-word vector register (128-bit width) now.

Don't we need more wider vector load instructions? Such as:
`vldu`
`vlq`

**Comment by a0u** [comment]
> Are the floating-point vector load instructions necessary?

The floating-point load instructions perform [NaN boxing](https://github.com/riscv/riscv-v-spec/blob/478919e3fccf71b55fa44bbf62140491c46307ce/v-spec.adoc#vector-code-nan-code-boxing) when writing to a wider destination register, as opposed to sign/zero-extension with integer loads.  They also provide a hint to microarchitectures that use an [internal recoded format]( https://github.com/ucb-bar/berkeley-hardfloat/blob/2f9cdc3b0e701b644b2ebb860ef2485b05b7d605/README.md#recoded-format) to represent float-point values.

**Comment by chenwei-tw** [comment]
@a0u Thanks for your response. I got it .
