### ISSUE TITLE
load/store and arithmetic operations with LMUL>1

### ISSUE THREAD

**Issue by MykolaMoshak** [riscv/riscv-v-spec#500]
I'm trying to understand how load/store and arithmetic operations are working with LMUL>1. 
Consider the following example:
settings: VLEN=32(32b vector registers), SEW=4(8b elements), LMUL=2(group 2 registers together)
int8_t input_arr_1[8] = {0, 1, 2, 3, 4, 5, 6, 7};
int8_t input_arr_2[8] = {8, 9, 10, 11, 12, 13, 14, 15};
int8_t output_arr[8] = {0};
a0 - 8, a1 - input_arr_1, a2 - input_arr_2, a3 - output_arr 

    vsetvli t1, a0, e8,m2  # vtype = 8-bit integer vectors, t1 = 8
    vle8.v v0, (a1)  # v0 = {0, 1, 2, 3}, v1 = {4, 5, 6, 7}, load first vector into two vector registers
    vle8.v v2, (a2)  # v2 = {8, 9, 10, 11}, v3 = {12, 13, 14, 15}, load second vector into two vector registers
    vadd.vv v4, v0, v2  # v4 = {8, 10, 12, 14}, v5 = {16, 18, 20, 22}
    vse8.v v4, (a3)  # Store both vector registers of 8b elements into destination vector

Afterwards the content of output_arr would be {8, 10, 12, 14, 16, 18, 20, 22}

The question is: Do the comments in the code describe the correct behaviour? If we use register grouping, then we load/store multiple vector registers as well as operate on them with only one instruction?

Thank you.

**Comment by kasanovic** [comment]
yes.
