### ISSUE TITLE
Unordered Index Operation Memory Ordering Description

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-v-spec#502]
From the discussion this morning, it seems that we need a little more in the description of unordered indexed stores.  We say that unordered indexed stores do not preserve memory element order within a single instruction.

I think we also want to say that any given store might be done more than once so that we can force the exception model to be in-order.  If we don't allow multiple stores, all element addresses will need to be checked for protection and translation before later elements are written to memory.  I think multiple writes (for the unordered version, not for the ordered version) has a very small cost since we've already said other harts don't see these stores in order.

It might be good to clarify that, when there are multiple identical indexes, there is no definition of which data is written to that index for the unordered instructions.

And I think we want to say that the order (and the data written with multiple identical indexes) does not have to be deterministic on the same implementation because that requires that restarting from any vstart value have the same element ordering as the original would have had.  Restarting might well, for example, complete the instruction as if it were an ordered indexed store so as not to add more possibilities and verification.

**Comment by kasanovic** [comment]
Resolved in https://github.com/riscv/riscv-v-spec/commit/511d0b84a3848de437fd01990d078feaa2871b11
