### ISSUE TITLE
{le} and {ge} do not render in anything besides body-text

### ISSUE THREAD

**Issue by BrianGraysonSiV** [riscv/riscv-v-spec#506]
Section 4.1 uses the {le} macro for less-than-or-equal, and in the body text, it renders just fine. However, in the section header and table of contents, it renders as:

![image](https://user-images.githubusercontent.com/59584749/86058244-2f1a5580-ba26-11ea-93fa-54aefe6ab4d9.png)

I think this is only an issue in the headers for 4.1 and 4.3.

**Comment by kasanovic** [comment]
It renders OK in asciidoctor.  I defer to asciidoc experts on what to do here.

**Comment by David-Horner** [comment]
This is (temporarily) resolved by removal of SLEN.

I think we can close.
