### ISSUE TITLE
vrgather SEW=8b only works up to 256 elements

### ISSUE THREAD

**Issue by respasa** [riscv/riscv-v-spec#520]
The spec already warns about SEW=8 in the text saying:

> When SEW=8, vrgather.vv can only reference vector elements 0-255.

However, this effectively makes 256b the largest VLEN where the ISA "fully/completely" works (at LMUL=8, SEW=8, that's VLMAX=256). Past that size, vrgather.vv starts progressively covering fewer cases. At VLEN=512b, vrgather works for LMUL=1,2,4 and all SEWs, but not for LMUL=8. At VLEN=1024, SEW=8 does not work for LMUL=4,8. Etc, etc. 

One proposal would be to define EMUL and EEW for the "index" source of vrgather based on the implementation VLEN of the machine for SEW=8, 

```
 if ( SEW == 8 && VLMAX > 256 ) {
   if ( LMUL == 8 ) { illegal instruction }
   else             { EEW = 2*SEW;  EMUL = 2*LMUL }
}
```
This would now "fix" vrgather for SEW=8 and LMUL=1,2,4. Obviously, this can't work for LMUL=8. And, yes, this only moves the goalpost from VLEN=2048 to VLEN=131072, but that feels more satisfactory...

**Comment by David-Horner** [comment]
I believe the current formulation is useful even for eew=8, so eliminating it is problematic.
It is possible to have another variant of vrgather that works on mixed vector for vs1 and vs2 if this use case is warranted.This could be added post v1.0 hopefully with the expedited process in place.


I see this as an after version V1.0 issue.

**Comment by kasanovic** [comment]
Software would have to know VLMAX to be able to use this form, so this would break software portability across different VLEN machines.

**Comment by kasanovic** [comment]
Proposal from task group is to add a vrgatherei16, which has fixed EEW of 16 for the index vector.  This in particular would support vrgather of >256 8b elements. Another benefit is lower register usage for the index vector for SEW>16b.
