### ISSUE TITLE
Raise illegal instruction exception under unsupported EEW in vector load whole register instructions or not

### ISSUE THREAD

**Issue by tingchou123** [riscv/riscv-v-spec#541]
No matter what EEW is, all vector load whole register instructions with the same EMUL should have the same result. Since the EEW is only a hint in these instructions.
I wonder what will happen if an unsupported SEW is used as a hint?
For example, execute vl1re256.v under ELEN=128.

**Comment by aswaterman** [comment]
The spec says "Implementations may raise illegal instruction exceptions on vl<nf>r instructions for EEW values that are not supported, or may treat them as a different EEW value (the architectural effect is the same)."

So, compilers need to avoid using EEWs that the ABI doesn't promise are supported.
