### ISSUE TITLE
Behavior when H extension present?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#548]
Has any thought been given yet to the interaction of this extension and the Hypervisor extension? At a minimum, I assume that mstatus.VS will be handled in a similar manner to mstatus.FS. What about other CSR state?

**Comment by aswaterman** [comment]
Yeah, it'll be analogous to the FP extension.

**Comment by kasanovic** [comment]
This should be addressed in the hypervisor spec.
