### ISSUE TITLE
Is fractional LMUL actually useful in vtype, vsetvl?

### ISSUE THREAD

**Issue by brucehoult** [riscv/riscv-v-spec#552]
[Edit: the below assumed #425 (which I like!) has adopted, which doesn't seem to have happened. Perhaps it provides more ammunition in favor of #425?]

Now that SEW refers to the largest element size used by an instruction and operands with smaller element size automatically take on a reduced EMUL (which might be less than 1), would you ever actually want an LMUL less than 1 for the SEW?

Why?

It no longer gains you more usable vector registers as it did when widening went from SEW to 2*SEW or 4*SEW. The only effect of vsetvli with mf8,mf4,mf2 now would seem to be to not use vector register length that you paid for.

We of course want fractional EMUL, but I think not fractional LMUL.

I suggest removing fractional LMUL from vsetvl and vtype.

**Comment by kasanovic** [comment]
#425 was not adopted.
