### ISSUE TITLE
Have to do overlapping and alignment checks in VRGATHEREI16.vv

### ISSUE THREAD

**Issue by Rolfy360** [riscv/riscv-v-spec#559]
case1: VLEN=128, VSEW=8, VMUL=1
vrgatherei16 vd, vs2, vs1
vs1 contains 16 e16  elements(fits in 2 VPRs), so vs1 should be even.

case2: VLEN=128, VSEW=64, VMUL=4
vrgatherei16 v8, v4, vs1
vs1 contains 8 e16 elements(fits in 1 VPR) and can not be v8, v9, v10.

**Comment by aswaterman** [comment]
“For any vrgather instruction, the destination vector register group cannot
overlap with the source vector register groups” — so in case 2, vs1 can’t
be v11, either.

**Comment by Rolfy360** [comment]
I think I should post this issue to spike, because current spike validates the relations among rd, rs2, rs1 using 

if (__builtin_expect(!(insn.rd () != insn.rs2 () && insn.rd () != insn.rs1 ()), 0))
  throw trap_illegal_instruction (0);

rd and rs1 should use is_overlapped(.) to check the overlap condition.

**Comment by Rolfy360** [comment]
post this issue to spike repository.
