### ISSUE TITLE
use vxrm rounding mode  for Vmulh*

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-v-spec#560]
Section 12.10 has note:

> Can consider changing definition of vmulh, vmulhu, vmulhsu to use vxrm rounding mode when discarding low half of product. There is no possibility of overflow in this case.

This should be decided before v1.0 finalization:

The functionality could be added post V1.0 by adding a bit in vxrm to enable the rounding in this class of instructions.
(further classes can be added by adding further bits; four classes for one more bit, eight for 2 more bits, etc.) 

#513

**Comment by kasanovic** [comment]
Keep as no rounding for now in v1.0.

Can add new fixed-point multiply instruction instead of new rounding mode, and this might have additional functionality including scaling/saturation.  Current *mulh* is not good match for fixed-point arithmetic.
