### ISSUE TITLE
vid.v redundant note

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#570]
The description of `vid.v` contains what I think is a redundant note:

_This constraint is to avoid WAR hazards in long vector implementations without register renaming, and to support restart_

I think this note was attached to a constraint that disallowed use of v0 as a destination when the instruction is masked which was removed in July last year.

**Comment by aswaterman** [comment]
Yeah, thanks, I should've removed that NOTE as part of b379d690d3acbb1b72320ce21f5bc32a7467878a
