### ISSUE TITLE
Are the reserved bits of vtype WARL?

### ISSUE THREAD

**Issue by respasa** [riscv/riscv-v-spec#575]
In this file: 

https://github.com/riscv/riscv-v-spec/blob/master/vtype-format.adoc 

bits XLEN-2:8 are described as "Reserved (write 0)".
 
Should this be interpreted as:
a) WARL (where legal would be zeros)?
b) Trap if attempting to write a non-zero value?
c) Other?

Whatever the answer, can we clarify in the doc?

thanks

roger.

**Comment by kasanovic** [comment]
While allowed to trap on reserved values, we don't want to mandate data-dependent traps.
Implementation can set vill if not a supported configuration.

vsetvli instructions have a 11b value written to vtype (sign bit of 12b imm field selects immediate/register forms of vsetvl) .
For future extension, we could view vtype as an 11b CSR, with additional CSRs added for more bits later.

**Comment by riking** [comment]
Note that as you cannot directly write to vtype, a WARL designation would be moot.

**Comment by kasanovic** [comment]
Changed to remove "write 0" in figure.  The current text has correct spec that unknown vtype setting will clear low order bits in vtype.
