### ISSUE TITLE
vconfig encoding in inst-table has src, dest registers

### ISSUE THREAD

**Issue by rkruppe** [riscv/riscv-v-spec#58]
While the size and interpretation of the immediate is still under debate, it seems pretty sure that the instruction (if we have it at all) should only have an immediate, no registers operands. The encoding in the table has vs1 and vd fields though. Those fields should probably be fixed to some bit pattern (e.g. vs1 = vd = v0) and other values made illegal instructions. Maybe those bits could also be repurposed.

**Comment by kasanovic** [comment]
Closing issue as new spec has different design.
