### ISSUE TITLE
Spec calrification on vid.v and vstart > 0

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-v-spec#580]
Should vid.v raise an illegal instruction exception when vstart > 0 ?

**Comment by David-Horner** [comment]
>Should vid.v raise an illegal instruction exception when vstart > 0 ?

In general no.

The implementation is not likely to interrupt this instruction in the middle, however, it is allowed to do so, and provide a vstart value for resume.
The implementation can trap if the provided vstart >0 is invalid, but that is true for any vector instruction,
