### ISSUE TITLE
vxsat in high bit like interrupt in cause.

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-v-spec#581]
Fortunately fcsr does not have this issue:

    Bits 31–8 of the fcsr are reserved for other standard extensions, including the “L” standard extension for decimal floating-point. If these extensions are not present, implementations shall gnore writes to these bits and supply a zero value when read. Standard software should preserve the contents of these bits.

3.9. Vector Control and Status Register vcsr The vxrm and vxsat separate CSRs can also be accessed via fields in the vector control and status CSR, vcsr.

As we are ponder the topic of reworking registers #

Perhaps vxsat should be in high order bit like TT (inrterrupt bit is) and reduce our csr load.

**Comment by kasanovic** [comment]
Current location in vcsr  allows rounding mode and saturation status to be set using one CSRI instruction.
