### ISSUE TITLE
Clarify vstart and Whole Register Move Instructions

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#589]
I think section 17.6 is unintentionally ambiguous with respect to the `vstart` CSR. Can you please clarify it? It states that:

> The instructions operate as if `EEW=8`, `EMUL = nr`, effective length `evl=VLEN/8 * EMUL`, regardless of current settings in `vtype` and `vl`.

So `vstart` is not mentioned. It then additionally says::

> Note: The usual property that no elements are written if `vstart ≥ vl` does not apply to these instructions.

This could be interpreted in two ways:
1. The value of `vstart` is ignored for these instructions; or:
2. `vstart` is not compared with `vl` because it is instead compared with `evl`, as defined above, and has its normal behavior.

Thanks.

**Comment by aswaterman** [comment]
To support taking interrupts in the middle of these instructions without needing to restart at the beginning, we want not to ignore vstart.  So option 2 is the intent.  I'll clarify the note.
