### ISSUE TITLE
readability of spec using GitHub UI

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#596]
One of the selling points of using asciidoc was that it renders well when using the github UI.  It seems that is slipping away; see e.g. https://github.com/riscv/riscv-v-spec/blob/master/vmem-format.adoc vs. its previous history.  I don't necessarily disagree with this strategy, but in my mind it is starting to lose points vs. sticking with LaTeX.

**Comment by kasanovic** [comment]
but even this is an improvement over latex source viewed in GitHub

**Comment by kasanovic** [comment]
Asciidoc is the new standard for RVIA specs.
Closing issue.
