### ISSUE TITLE
Minor issue with normativity in Section 7.2

### ISSUE THREAD

**Issue by riking** [riscv/riscv-v-spec#599]
The note beginning "A profile may place a upper limit on the maximum required index EEW ... in which case an illegal instruction exception can be raised if the EEW is not supported." seems to be confused about the role of requirements and profiles. The normative text should allow the load/store instruction to raise an exception for unsupported index EEWs, with profiles specifying what particular index EEWs (e.g. up to XLEN only) must be supported.

**Comment by knightsifive** [comment]
I too find that note confusing (upper limit on the maximum required?) or in need of copyediting ("a upper"). It probably should be reviewed in tandem with a related note below:
> Note | In base V extension, only index widths up to XLEN must be supported.

I think this is one of several outstanding issues concerning the definition of the "base" V extension and its relationship with "profiles".
