### ISSUE TITLE
How to define configuration for byte and double vectors?

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-v-spec#6]
2.1.1. vregcfg[6:0]
If `s` type is byte, then `q` is not greater than 32 bit word/float.
If `q` type is double, then `s` is not less than 16 bit short int.

How to define configuration that effectively maps both byte and doubles?

**Comment by colinschmidt** [comment]
Fully configurable vector element width will only be supported in the extended encoding see https://github.com/riscv/riscv-v-spec/blob/b77b848a5e4f613a9fd60a139e3728807a735e22/v-spec.adoc#411-vewn
