### ISSUE TITLE
Insn encoding inconsistencies between vmsCMP/vmfCMP

### ISSUE THREAD

**Issue by riking** [riscv/riscv-v-spec#600]
There is a strange inconsistency between the vector-integer comparison encodings and the vector-float comparison encodings. Proposed fix inline in the table below, with the only open question being where to place `vmfge`.

funct6 | V | X | I | op | funct6 | V | X | op | funct6 | V | F | op 
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
011000 | V | X | I | vmseq | 011000 | V |   | vmandnot | 011000 | V | F | vmfeq
011001 | V | X | I | vmsne | 011001 | V |   | vmand | 011001 | V | F | ~~vmfle~~ **vmfne**
011010 | V | X |   | vmsltu | 011010 | V |   | vmor | 011010 |   |   |  
011011 | V | X |   | vmslt | 011011 | V |   | vmxor | 011011 | V | F | vmflt
011100 | V | X | I | vmsleu | 011100 | V |   | vmornot | 011100 | ~~V~~ | ~~F~~ | ~~vmfne~~
011101 | V | X | I | vmsle | 011101 | V |   | vmnand | 011101 | **V**  | F | ~~vmfgt~~ **vmfle**
011110 |   | X | I | vmsgtu | 011110 | V |   | vmnor | 011110 |   | **F**  | **vmfge (?)**
011111 |   | X | I | vmsgt | 011111 | V |   | vmxnor | 011111 |   | F | ~~vmfge~~ **vmfgt**

**Comment by kasanovic** [comment]
I understand the desire for consistency, and appreciate this might have been a somewhat better choice for aesthetic reasons, but in practice this has unobservable difference in logic cost.  At this point, would need a larger win to churn encodings.
