### ISSUE TITLE
All mask write operations are "tail agnostic"

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-v-spec#602]
To simplify complex mask register implementations, proposal is to treat all mask register writes as "tail agnostic" regardless of "ta" setting in vtype.  The belief is that software does not usually need "tail undisturbed" case, and it would simplify renamed implementations and those with micro architecturally optimized mask register implementations.

**Comment by David-Horner** [comment]
A 2ndary but significant benefit of restricting mask ops to agnostic is the prominance provided to this idea.
Undisturbed as an option for non-mask ops provides an immediately recognizable benefit. However the cost is not as apparent. And the cost is not just hardware implementation but also software exposures.

Stipulating agnostic for mask writes highlights the distinctions and affords opportunity to better understand tradeoffs.
