### ISSUE TITLE
mapping element of widening result when lmul < 1

### ISSUE THREAD

**Issue by jeremyccl** [riscv/riscv-v-spec#605]
Hi 

As v0.9 add new case of fractional LMUL, not quite sure what's the element map result for vwop.

If my design is SLEN = VLEN = 128bit and set LMUL = 1/2 & sew32, after executing a vwmac.vv v2, v4, v8,
as vd EEW = SEW*2 and EMUL = LMUL *2 = 1/2 * 2 = 1, vwmac will update v2 [127:64][63:0]. 
Is my result correct?

**Comment by kasanovic** [comment]
yes
