### ISSUE TITLE
minor typos in vnew.adoc

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#61]
In section 5, the vtype layout picture is missing bit 4.  Presumably should be a reserved bit.

In section 13.8, the vmerge.vi instruction has an operand vs2 instead of imm.

In section 14, refers to VNSR/VNSRA which should be VSRN/VSRAN to be consistent with the rest of the document.

**Comment by aswaterman** [comment]
Thanks, will fix.
