### ISSUE TITLE
Slight inconsistency on constraints on ELEN for Base V Extension compliance

### ISSUE THREAD

**Issue by MarkHillHuawei** [riscv/riscv-v-spec#612]
In the section on Implementation-defined Constant Parameters the only constraints on ELEN are "ELEN ≥ 8, which must be a power of 2" with a note that "Profiles may set further constraints on these parameters, for example, requiring that ELEN ≥ max(XLEN,FLEN), or requiring a minimum VLEN value".  

However in the description of SEW the spec says: "In the base vector V extension, only SEW up to ELEN = max(XLEN,FLEN) are required to be supported. Other profiles may impose different constraints on ELEN." which suggests that ELEN must be  ≥ max(XLEN,FLEN) to be compliant.

**Comment by knightsifive** [comment]
... compliant *with the "base" V extension*.

My reading is that the earlier text is leaving open the possibility of "non-base" V extensions that support smaller sets of data widths.

I think the underlying question is, what is the "base" V extension? This needs to be resolved for v1.0.
