### ISSUE TITLE
About vmv.x.s should be vs1 = 0?

### ISSUE THREAD

**Issue by luyahan** [riscv/riscv-v-spec#625]
```
vmv.x.s rd, vs2 # x[rd] = vs2[0] (rs1=0)
```
vmv.x.s  belong to VWXUNARY0  and OPMVV 
But OPMVV has only vs1 no rs1, see :
```
  funct6   | vm  |   vs2    |    vs1   | 0 1 0 |  vd/rd  |1010111| OP-V (OPMVV)
```
So i think `vmv.x.s rd, vs2  # x[rd] = vs2[0] (rs1=0)` should be fixed to `vmv.x.s rd, vs2  # x[rd] = vs2[0] (vs1=0)` or 
encode vmv.x.s to VRXUNARY0  and OPMVX?
```
  funct6   | vm  |   vs2    |    rs1   | 1 1 0 |  vd/rd  |1010111| OP-V (OPMVX)
```

**Comment by kasanovic** [comment]
Yes, should be vs1=0 in comment.
