### ISSUE TITLE
Could not find EEW encoding to whole register moves

### ISSUE THREAD

**Issue by alextsao1999** [riscv/riscv-v-spec#628]
"Added EEW encoding to whole register moves and load/stores to support microarchitectures with internal data rearrangement."

When I see the whole vector regsiter move, there seems to be no how to encode EEW?

https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#176-whole-vector-register-move

**Comment by kasanovic** [comment]
Clarified by https://github.com/riscv/riscv-v-spec/commit/c841730fe683243531a0d5ffa087b584683d6e57
