### ISSUE TITLE
Section 7.2: are vector offsets in gather/scatter signed or unsigned?

### ISSUE THREAD

**Issue by respasa** [riscv/riscv-v-spec#637]
Section 7.2 says:

> If the vector offset elements are narrower than XLEN, they are **zero-extended** to XLEN before adding to the base effective address. If the vector offset elements are wider than XLEN, the least-significant XLEN bits are used in the address calculation.

Is this really what we want? Offsets can not be negative?

**Comment by kasanovic** [comment]
Yes, we changed this in one meeting.
