### ISSUE TITLE
current stable v0.10 not "latest"

### ISSUE THREAD

**Issue by sg-** [riscv/riscv-v-spec#646]
Just a github-ism but if you point at https://github.com/riscv/riscv-v-spec/releases/latest is reverts to v0.9 becuase v0.10 is marked as a pre-release. However, the readme.md calls v0.10 current stable. 

Can an admin change the tick box from pre-release to release to we can use https://github.com/riscv/riscv-v-spec/releases/latest to point at the most recent version of the spec?

**Comment by aswaterman** [comment]
Done
