### ISSUE TITLE
consistent words for unordered/ordered index load/store

### ISSUE THREAD

**Issue by chihminchao** [riscv/riscv-v-spec#652]
There are two types in v-spec.
   The first is "indexed-unordered" in [encoding table](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#72-vector-loadstore-addressing-modes) and  "unordered indexed"/"unordered-indexdex" in [complete instruction list](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#76-vector-indexed-instructions).
It should be better to use the same phrase.

**Comment by kasanovic** [comment]
Agree, will change.
