### ISSUE TITLE
Unsupported vtype when lmul<1

### ISSUE THREAD

**Issue by fuyao-wong** [riscv/riscv-v-spec#673]
In section 3.3, spec_0.10 says 
_For a given supported fractional LMUL setting, implementations must support SEW settings between SEWLMUL1MIN and
LMUL * SEWLMUL1MAX, inclusive._
Does it means that:
1.unsupported vtype will set vill
   when lmul=1/8,  sew must be set 8,  if not, vill will be set,  is it?
2.supported vtype, but eew of instruction does not belong to [SEWLMUL1MIN,LMUL * SEWLMUL1MAX]
   when vlen=128, lmul=1/8,  sew=8, for vle64.v instruction, eew is 64, the load data is wider than maximum width that  vtype can express(128x1/8=16), this instruction will be illegal or not?

**Comment by aswaterman** [comment]
1. That sentence only states which fractional LMUL values _must_ be supported for a given SEW; it does not state which ones _must not_ be supported.  Implementations might support more than the required minimum.

2. I don't understand what you mean by "the load data is wider than the maximum width that vtype can express".  This is a legal combination.

**Comment by nick-knight** [comment]
> Vector loads and stores have an EEW encoded directly in the instruction. The corresponding EMUL is calculated as EMUL = (EEW/SEW)*LMUL. If the EMUL would be out of range (EMUL>8 or EMUL<1/8), the instruction encoding is reserved. The vector register groups must have legal register specifiers for the selected EMUL; the instruction encoding is otherwise considered reserved.

If LMUL = 1/8, SEW = 8, then for vle64.v you have EEW = 64 and EMUL = (64/8)*(1/8) = 1. This is valid.

If you have VLEN = 128, then LMUL = 1/8 and SEW = 8 implies that VL is in {0, 1, 2}. So the `vle64.v` will populate none, half, or all of a single vector register.

**Comment by fuyao-wong** [comment]
thanks
As spec(3.3) says
_For a given supported fractional LMUL setting, implementations must support SEW settings between SEWLMUL1MIN and
LMUL * SEWLMUL1MAX, inclusive._
SEW between SEWLMUL1MIN and LMUL * SEWLMUL1MAX, inclusive, must be supported. it means SEW settings are only relevant to SEWLMUL1MIN, LMUL, SEWLMUL1MAX, and not relevant to VLEN, that will be easy for programers.  issue 656 has shown
https://github.com/riscv/riscv-v-spec/issues/656#issuecomment-805357460
then, unsupported settings when lmul<1 will set VILL in vtype or not?
