### ISSUE TITLE
the result about vasub

### ISSUE THREAD

**Issue by wzy971210** [riscv/riscv-v-spec#674]
Hi, I ask this question previously. Please see [this](https://github.com/riscv/riscv-v-spec/issues/659)

And you said that the difference between vasub and vasubu is the singed/unsigned shifting.

However,when I try to figure out this question on Spike, to see the result of this instruction , I see the result 0x8000, not 0x0000., which means singed addition and singed shifting. 
`0x7fff - 0x8000 = signed(0x7fff) - signed(0x8000) = 0x00007fff - 0xffff8000 = 0x0000ffff; (signed(0x0000ffff) >> 1) + 1 = 0x8000`
So, please rethink and confirm the result about vasub?

![image](https://user-images.githubusercontent.com/44627319/118105767-65c74780-b40f-11eb-80fb-6347a2d7fce0.png)

**Comment by aswaterman** [comment]
Let's move the discussion back to the other thread.
