### ISSUE TITLE
inconsistencies in UIMM notation

### ISSUE THREAD

**Issue by ubc-guy** [riscv/riscv-v-spec#679]
UIMM5 is undefined, should be just UIMM:
 vnclipu.wi vd, vs2, uimm, vm # vd[i] = clip(roundoff_unsigned(vs2[i], uimm5))
 vnclip.wi vd, vs2, uimm, vm  # vd[i] = clip(roundoff_signed(vs2[i], uimm5))

UIMM[4:0] should be just UIMM:
 vslideup.vi vd, vs2, uimm[4:0], vm  # vd[i+uimm] = vs2[i]
 vslidedown.vi vd, vs2, uimm[4:0], vm # vd[i] = vs2[i+uimm]

**Comment by aswaterman** [comment]
Agreed on both counts.
