### ISSUE TITLE
overlap constrains when lmul<1

### ISSUE THREAD

**Issue by fuyao-wong** [riscv/riscv-v-spec#685]
As spec_0.10(5.2 section) says:
_A destination vector register group can overlap a source vector register group only if one of the following holds:
- The destination EEW equals the source EEW.
- The destination EEW is smaller than the source EEW and the overlap is in the lowest-numbered part of the source register group (e.g., when LMUL=1, vnsrl.wi v0, v0, 3 is legal, but a destination of v1 is not).
- The destination EEW is greater than the source EEW, the source EMUL is at least 1, and the overlap is in the highest numbered part of the destination register group (e.g., when LMUL=8, vzext.vf4 v0, v6 is legal, but a source of v0, v2, or v4 is not).

that means only 3 situations can be allowed, anything else is illegal for overlap. i have 2 questions:
for lmul<1
1.The destination EEW is greater than source EEW(widden).
   vsetvli x0, x1, e8, mf2
   vwop.vv  v8, v8, v10    // this instruction will be illegal, is it?  (source EMUL is smaller than 1, source and destination EEW are not equal)
   vwop.wv v8, v8, v10    // this instruction will be legal, is it?  (source EEW equals destination EEW)
2.The destination EEW is smaller than source EEW(narrow).
   vsetvli x0, x1, e8, mf2
   vnop.wv  v8, v8, v10    // this instruction will be illegal, is it?  (destination group is lowest-numbered part of source register group)

**Comment by aswaterman** [comment]
In general, I recommend running this code on Spike rather than asking for clarification here.  It is more likely to be correct in response to questions about code example than the humans are :)

The first example is indeed illegal because of the third rule.

The second example is indeed legal because of the first rule.

But the third example is _legal_ because of the second rule.

**Comment by fuyao-wong** [comment]
thanks
