### ISSUE TITLE
Is zve32d supported ?

### ISSUE THREAD

**Issue by chihminchao** [riscv/riscv-v-spec#695]
The sec. 8.1 says
"The Zve32d and Zve64d extensions require the scalar processor to implement the D extension, and implement all vector floating-point instructions (Section Vector Floating-Point Instructions) for floating-point operands with EEW=32 or EEW=64 (including widening instructions and conversions between FP32 and FP64)."
but it is not included in the beginning list.

**Comment by kasanovic** [comment]
Zve32d is a typo - removing.
