### ISSUE TITLE
zve64* and zve32* complicated the arch string parser logic

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-v-spec#697]
Currently we don't have any extension name contain digit, zve64* and zv32* are the first extension named with digit, that cause the current arch string parser logic, since we assume the any digit are version before*, parser logic will become complicate without this assumption.

Could you consider to rename the extension name for exclusive digits?

* LLVM and GCC parser are using similar logic to parse arch string, go to parsing version mode once got digit.

**Comment by nick-knight** [comment]
The ISA Manual (I:25.6) says:
> Standard extensions can also be named using a single “Z” followed by an alphabetical name and an optional version number.

My reading of this implies that extension names like `Zve32` are illegal.

**Comment by David-Horner** [comment]
Easily solved with zvesixtyfour?

**Comment by kito-cheng** [comment]
@nick-knight Hmmm, yeah, ISA spec seems not forbid extension name contain with digit, but with this constraint parser would be easier to implement.

@David-Horner `zvesixtyfour` good to me, there is no digit in the name :P but I know it's really verbose than zv64*...

**Comment by aswaterman** [comment]
@kito-cheng It's implicitly forbidden by the current spec, because the current spec says the number will parse as a version number (i.e. Zve64 will be unambiguously interpreted as Zve, version 64).

**Comment by kito-cheng** [comment]
Some offline chat with @aswaterman :
Kito: I know `zve64` is pretty ambiguous with version, so how do you think about `zve64x`?
Andrew: I think Krste needs to change the ISA strings to avoid numbers, changing parser doesn't makes sense to me, because it violates the spec
...
Kito: but I admit `zve64*`/`zve32*` is really expressive
Andrew: It's unfortunate that it's both expressive and invalid, maybe zved and zvew (doubleword / word)

**Comment by aswaterman** [comment]
PS.  Given that we require `_` to separate multi-letter extensions, I agree that something like `zve64x` would parse unambiguously, because of the `x`.  `zve64x2p0` would give a version number in this case.

**Comment by DSHorner** [comment]
On 2021-06-29 1:44 a.m., Andrew Waterman wrote:
>
> PS. Given that we require |_| to separate multi-letter extensions, I 
> agree that something like |zve64x| would parse unambiguously, because 
> of the |x|.
>

> |zve64x2p0| would give a version number in this case.
>
Is the version number 2p0 in this case? asking for clarification?


there is roman numerals: XXXII and LXIV .

Greek - like roman numerals but more characters if modern form used.

There are other numeral representation.

三十 二 and 六十 四 for 32 and 64 respectively in Mandarin/Cantonese.

. סד and ל ב ‎Hebrew for 32 and 64 respectively


The strings are assumed to be unicode, right?

I prefer the chinese in that it is: very expressive and intuitive; 
reasonably concise; and acknowledges  major efforts from Asian participants.

I am open to other Asian representations, but the alternate dialects are 
many and represent fewer portions of the populations there.

**Comment by kito-cheng** [comment]
Created a PR for clarify the rule.
https://github.com/riscv/riscv-isa-manual/pull/718
