### ISSUE TITLE
Remove calling convention note from v-spec

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-v-spec#709]
@Hsiangkai and me is working on proposing new vector calling convention, which means we will have dual calling convention for vector registers, the description might not 100% match the description of appendix B, so I would suggest remove that chapter and let return psABI document.

**Comment by kasanovic** [comment]
I will add a note indicating this is not authoritative or being ratified, and refer to the new spec in preparation.  But until there is a new spec to point at, I will keep this in as placeholder as it helps explain the assembler code examples.
