### ISSUE TITLE
Unsigned segment loads?

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#72]
In section 7.8.1 it says
    vlseg<nf>{b,h,w,e}.v vd, (rs1),  vm   # Unit-stride segment load template
which implies that we have only signed segment loads.  The encoding supports unsigned segment loads, and it would appear that they should be supported, so this just seems to be a typo in the description.

Similarly in 7.8.2 for strided segment loads and 7.8.3 for indexed segment loads.

**Comment by kasanovic** [comment]
Should have included unsigned variants.Fixed in text.
