### ISSUE TITLE
Does `vl*re64.v` available for zve32* extension 

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-v-spec#724]
Spec say the EEW is hint for the whole register load in the note, but isn't clear does it valid instruction when we don't support EEW=64, like `zve32x` or `zve32f`.

---
7.9. Vector Load/Store Whole Register Instructions
> ... The full set of EEW variants is provided so that the encoded EEW can be used as a hint to indicate the destination register group will next be accessed with this EEW, which aids implementations that rearrange data internally.

**Comment by kasanovic** [comment]
Implementations can trap on EEW they don't support.  It is only a hint, not a RISC-V HINT.

The hint is useless if machine doesn't have the datatype.
