### ISSUE TITLE
FPR reuse the lower part of VPR

### ISSUE THREAD

**Issue by jovireal** [riscv/riscv-v-spec#725]
when both vector extension and F extension are supported, is it possible to reuse the lower part of vector register for floating-point register? As in hardware design, scalar FP operation and vector FP operation usually share the same issue pipe and computation logic for area efficiency. by reusing the register source, the operand mux, the read port/write port logic and the result fanout can be largely reduced.

**Comment by jnk0le** [comment]
0.6 vectors were shared with fp. Now it's separate. 

Sharing pipeline for scalar and vector can also have disadvantages. Like not being able to perform scalar and vector operation in paraller or not having 'extra' read port for scalar-vector ops.

**Comment by kasanovic** [comment]
There was extensive discussion over course of development leading to current design.  Spec section 5.1 Scalar operands has some rationale on this.
