### ISSUE TITLE
about the different of vs1 and vs2 while in use

### ISSUE THREAD

**Issue by lj-k** [riscv/riscv-v-spec#733]
I noticed some instruction use vs2 for source reg. even their is only one source vector reg.  
for example the slideup slidedown insturction.  vslideup.vx vd, vs2, rs1 , vm
do there has any rules while determining to use vs1 or vs2?

**Comment by kasanovic** [comment]
The spec says which one to use.

The rationale is that on the scalar side, rs1 is used for at least one of the scalar register operands.   So using vs2 for the primary vector operand provides greater regularity when you need one of each.
