### ISSUE TITLE
Order of registers in FP-FMA instrs are different than the rest of FVV instrs

### ISSUE THREAD

**Issue by 0x6770** [riscv/riscv-v-spec#734]
I noticed that, although `vfmadd` and  `vfmul` both belong to FVV instruction format, their have different order of registers. 
In the spec, Floating-Point Fused Multiply-Add instructions have registers ordered in rd, rs1, rs2, while the rest of FVV instructions have registers ordered in rd, rs2, rs1. 
Is this design by intension? Would it be nicer to have consistence across instructions of the same format?

```asm
vfmadd.vv vd, vs1, vs2, vm
vfmul.vv  vd, vs2, vs1, vm
```

**Comment by kasanovic** [comment]
Yes, please see rationale in the spec in Section 10:
NOTE: For ternary multiply-add operations, the assembler syntax always
places the destination vector register first, followed by either `rs1`
or `vs1`, then `vs2`.  This ordering provides a more natural reading
of the assembler for these ternary operations, as the multiply
operands are always next to each other.
