### ISSUE TITLE
Bug in Example A.4

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-v-spec#741]
Example A.4 decrements a0 in the instruction after the vle8.v and then uses a0 again in the second vsetvli instruction.  Often the second last iteration of the loop will get a too-small result and the last iteration will get zero that way.  I think the second vsetvli should be written with rd=x0 and rs1=x0 so that vl isn't changed.

**Comment by aswaterman** [comment]
Agreed, and the left-shifting of `t0`, which previously depended on the `vsetvli`, does the right thing, since `t0` still contains `vl` at that point.
