### ISSUE TITLE
Inconsistent sequence for vs1 and vs2

### ISSUE THREAD

**Issue by eopXD** [riscv/riscv-v-spec#743]
Currently, operation in spec is inconsistent for the sequence of vs1 and vs2.

For example...

In `vadd` and `vsub`:

```
vadd.vv vd, vs2, vs1, vm   # Vector-vector
vsub.vv vd, vs2, vs1, vm   # Vector-vector
```

In `vmacc`:

```
vmacc.vv vd, vs1, vs2, vm    # vd[i] = +(vs1[i] * vs2[i]) + vd[i]
```

May I ask if there is any specific intention behind this?

**Comment by eopXD** [comment]
Hi Nick,

Thank you for your response. I understand the intention for a more natural reading in ternary operations, but why not unify the sequence of both?

Wouldn't unifying the instruction encoding let users have a more organized understanding to RVV? I think unifying either to `vop.vv vs1 vs2` or `vop.vv vs2 vs1` is ok as long as naming across operations become consistent.

**Comment by jim-wilson** [comment]
The encoding is irrelevant to assembly language programmers.  All that matters is that if you want to perform an operation on two values, then you can type in the obvious code and it will work.  And it does.  "vsub v8, v9, v10" puts v9 minus v10 in v8 as expected.  Which operand is vs1 and which one is vs2 is irrelevant.

The encoding only matters to the hardware designers who implement the instruction decoding pipeline stage.  And here, apparently swapping the operands for the binary operations allow us to reduce the number of gates required for the decoder, which is a good thing, and worth the minor inconvenience of having the swapped operands.

**Comment by eopXD** [comment]
I see. Thank you Jim for the explanation.
