### ISSUE TITLE
suggest using listing block instead of source block

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#75]
I get many errors trying to generate an html file using the asciidoc program.
asciidoc: ERROR: v-spec.adoc: line 100: undefined filter attribute in command: source-highlight -f xhtml -s {language} {src_numbered?--line-number=' '} {src_tab?--tab={src_tab}} {args=}
The generated output is missing all source blocks.

The asciidoc docs say that source blocks require a language, so "[source]" is not valid input because the language is missing.  I would suggest using a listing block instead, when there is no source language to specify, which you can get just by deleting the [source] line.

**Comment by kasanovic** [comment]
I vaguely remember having formatting issues before that [source] fixed, but can't see any issue now, so reverting to plain listing. Now compiles without asciidoc errors. Thanks!
