### ISSUE TITLE
Reduced Vector Register Count in Zve*

### ISSUE THREAD

**Issue by fabianpedd** [riscv/riscv-v-spec#753]
Why would there be no option for a reduced vector register count in the embedded extensions Zve*, similar to RV32E (which only features 16 scalar registers)? At least I was not able to find any mention of this in the standard. Something similar was suggested in [this](https://ieeexplore.ieee.org/abstract/document/9232940) paper. 

One can reduce the VLEN in order to make the overall V state smaller, but wouldn't reducing the number of individual registers also help in lowering the footprint of the implementation? Thanks in advance for any guidance on this topic :)

**Comment by aswaterman** [comment]
There is no such option currently offered. The P extension is probably more appropriate than the V extension for situations where absolute area is more important than the ratio of perf to area.
