### ISSUE TITLE
a small suggestion for the descriptions of vnclip

### ISSUE THREAD

**Issue by kaitoukito** [riscv/riscv-v-spec#755]
In manual V1.0, Page58
"For vnclip, ... if the result would overflow the destination viewed as a signed integer"
may better be described as
"For vnclip, ... if the result would overflow or underflow the destination viewed as a signed integer"
as it is signed.

**Comment by aswaterman** [comment]
That doesn’t match my understanding of common use of the term “underflow”, which normally refers to a number’s magnitude becoming too small, resulting in a loss of precision. By contrast, exceeding the data type’s range is normally called “overflow”, regardless of the direction.

**Comment by kaitoukito** [comment]
> That doesn’t match my understanding of common use of the term “underflow”, which normally refers to a number’s magnitude becoming too small, resulting in a loss of precision. By contrast, exceeding the data type’s range is normally called “overflow”, regardless of the direction.

Thanks for your reply:)
