### ISSUE TITLE
inconsistent fault-only-first instruction naming

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#76]
The unit-stride fault-only-first instructions are for instance vlbff.v.  The unit-stride segment fault-only-first instructions are for instance vlsegff1b.v.   They have the ff in a different place, after and before, the load size.  That looks a little odd, and might be confusing to assembly language programmers.

**Comment by kasanovic** [comment]
Agreed, should be consistent.  Changing to always have ff last.
