### ISSUE TITLE
Should the sc.d fail when pair with lr.w with same address?

### ISSUE THREAD

**Issue by zhongchengyong** [riscv/riscv-v-spec#764]
should sc fail when pair with lr which reserve same address but different size? e.g.
```
la a0, symbol
lr.w a1, (a0)        # lr with word
sc.d a1, x0, (a0)    # sc with dword
```
Should the sc.d instruction succeed or fail?

**Comment by aswaterman** [comment]
I think you posted this on the wrong repository's issue tracker.  Anyway, it is UNPREDICTABLE whether the sc.d succeeds.  https://github.com/riscv/riscv-isa-manual/blob/ea38395ec05bd7a958ac81c532eaa90f04e82e28/src/a.tex#L175-L176

**Comment by zhongchengyong** [comment]
I see. Thanks for your explanation.
