### ISSUE TITLE
Could we have an additional instruction to round a float to an integral value?

### ISSUE THREAD

**Issue by JerryShih** [riscv/riscv-v-spec#773]
It is just like the std::nearbyint() which could round a float value to an integral value.
https://www.cplusplus.com/reference/cmath/nearbyint/

Now, we need to do something like:
```
vfcvt.x.f.v  v2, v1 // convert float to integer with rounding
vfcvt.f.x.v  v3, v2 // convert integer back to float
```

ARM already has a instruction `VRINT` for this.
https://developer.arm.com/documentation/100076/0100/a32-t32-instruction-set-reference/floating-point-instructions--32-bit-/vrint--floating-point-

**Comment by nick-knight** [comment]
Related: https://github.com/riscv/riscv-v-spec/issues/623
