### ISSUE TITLE
What vector reduction operations behave when lv > 0 and 0's mask is used?

### ISSUE THREAD

**Issue by lhtin** [riscv/riscv-v-spec#777]
Sorry, I can't get the reduction operations behavior when vl > 0 and 0's mask is used from the spec[1]. Is the current mask policy used on vd[0] element in that condition? Thanks.

[1] https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#vector-reduction-operations

**Comment by aswaterman** [comment]
"Inactive elements from the source vector register group are excluded from the reduction, but the scalar operand is always included regardless of the mask values."

So, the reduction still occurs (trivially) and vd[0] is written.

**Comment by lhtin** [comment]
Thanks.
