### ISSUE TITLE
unordered indexed segmented stores?

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#78]
There is no vsuxseg listed.  It isn't clear if this is an oversight or deliberate.

**Comment by kasanovic** [comment]
Good point, and brings up the issue where segments can overlap, also for strided segments.
Needs more thought and discussion.

**Comment by kasanovic** [comment]
Strided should behave same as indexed.  On indexed, cannot detect overlap at issue time, so cannot make illegal instruction.   Strided case can be detected at runtime, and then hardware could potentially optimize away redundant stores.  PoR: Strided/indexed segment stores are only provided in ordered form.
