### ISSUE TITLE
Confused about note of mask/tail agnostic/undisturbed in spec

### ISSUE THREAD

**Issue by jlong299** [riscv/riscv-v-spec#791]
In spec 1.0, there is a note in 3.4.3: "An out-of-order implementation can choose to implement tail-agnostic + mask-agnostic using tail-agnostic + mask-undisturbed to reduce implementation complexity".
Why can the latter reduce implementation complexity? In my understanding, the mask-agnostic can choose to write 1s, but mask-undisturbed has to read the old physical register in a OOO, which infers that the former is with less implementation complexity.
Thanks.

**Comment by aswaterman** [comment]
Supporting mask-undisturbed is mandatory (in that implementations are required to support `vma=0`).  Supporting mask-agnostic by writing 1s is optional.  Supporting two things is more complexity than supporting only one thing.
