### ISSUE TITLE
Why dose whole register store has only EEW=8 encoded

### ISSUE THREAD

**Issue by jlong299** [riscv/riscv-v-spec#798]
It is said in spec that load whole register has full set of EEW variants as a hint to aid internally data rearrangement. Why doesn't the store whole register need the hint EEW in the case of internal data rearrangement?
Thanks.

**Comment by jlong299** [comment]
Thanks a lot.  What if the register 0-1 has EEW of 16 and register 2-3 has EEW of 32, and the store whole register wants to put register 0-3 into memory? Does that mean I need extra hardware to record the vtype of all registers?

**Comment by aswaterman** [comment]
It's never necessary to use extra hardware to record the vtype of each register.  See, for example, the Spike implementation of RVV, which does no such thing.

**Comment by jlong299** [comment]
Can one store whole register instruction operate on multiple registers with different EEW settings?

**Comment by nick-knight** [comment]
Yes, software can do this.

**Comment by jlong299** [comment]
Got it. Thank you so much.

**Comment by jlong299** [comment]
So if vstart > 0, the number of prestart elements of Store Whole Register instruction should be calculated based on EEW = 8 ?

**Comment by aswaterman** [comment]
That's right.
