### ISSUE TITLE
vnclip operands reversed?

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#80]
Section 13.6 has
```
# Narrowing signed clip,  vd[i] = clip(round(vs1[i] + rnd) >> vs2[i])
#                                     SEW           2*SEW                 SEW
```
which treats vs1/rs1/imm as a 2*SEW value which doesn't make much sense.  A vector reg can be 2*SEW but rs1/imm are not normally treated as 2*SEW.  Also, the previous section for scaling shift has
```
vssrl.vv vd, vs2, vs1, vm   # vd[i] = ((vs2[i] + round)>>vs1[i])
```
which is more sensible looking but has reversed operands from the vnclip definition.  I think the vnclip definition is wrong.

**Comment by kasanovic** [comment]
Yes, vnclip was incorrect. Fixing.  Thanks.
