### ISSUE TITLE
Policy for vector load/store instructions

### ISSUE THREAD

**Issue by eopXD** [riscv/riscv-v-spec#800]
Vector load instructions have `vd` as its destination vector register, so I assume they follow the policy settings in `vta` and `vma`. Vector store instructions don't have a destination vector register, so I assume these instructions perform indifferently across policy settings.

Is my interpretation correct?

**Comment by aka2en** [comment]
Yes, it is correct.

**Comment by eopXD** [comment]
Thank you for the swift reply.
