### ISSUE TITLE
Can mask register be accessed with different EEW ?

### ISSUE THREAD

**Issue by jlong299** [riscv/riscv-v-spec#809]
At start of chapter 4 of spec v1.0, there is a note "For example, microarchitectures can track the EEW with which a vector register was written, and then insert additional scrambling operations to rearrange data if the register is accessed with a different EEW.". 
So, for the case of mask register, can mask register be accessed with different EEW?  Such as EEW = 32? (In a internally data rearranged machine it could lead to dedicated scrambling logic for mask register).
Thanks.

**Comment by aswaterman** [comment]
Yes, it is well defined to do so.  The text you quoted is about a style of microarchitecture and doesn't have any implications for the architecturally visible behavior.
