### ISSUE TITLE
Question about vl

### ISSUE THREAD

**Issue by huikmn** [riscv/riscv-v-spec#815]
In the riscv-v-spec, vl can be set to a value within 0-vlmax. In order to reduce the hardware complexity, can i add one more contraint to limits vl <= vlen/sew?
So, even VSET instruction sets vlen/sew < vl <vlmax, it still makes vl = vlen/sew. Also rd will be update to vlen/sew。In this case showed in riscv-v-spec works with this extra constraint. 
![屏幕截图 2022-07-28 102532](https://user-images.githubusercontent.com/110142725/181406862-7ab2e6e2-0efd-487e-b49c-2913ad543136.png)

I want to ask if this extra constraint is acceptable, will this cause problem of consistency bewteen software and hardware?

**Comment by aka2en** [comment]
VLMAX equals to (LMUL * VLEN / SEW). If VL is restricted to (VLEN / SEW), that will lose the benefit of vector register grouping.

**Comment by huikmn** [comment]
> VLMAX equals to (LMUL * VLEN / SEW). If VL is restricted to (VLEN / SEW), that will lose the benefit of vector register grouping.

I know it will lose the benefit of register group. But it also reduce the comlexity of hardware. If this policy is acceptable, at least I have one more choice to choose between the benefit of register group and the comlexity of hardware.

**Comment by aswaterman** [comment]
No, this would be a nonstandard custom extension, rather than standard V or Zve*.

Making register groups optional would make them unusable by standard software, which would undermine the motivation for the feature.

**Comment by topperc** [comment]
Even with that constraint, wouldn't the widening instructions like vwadd still be able to produce a result that required 2 registers to hold the result?

**Comment by huikmn** [comment]
> No, this would be a nonstandard custom extension, rather than standard V or Zve*.
> 
> Making register groups optional would make them unusable by standard software, which would undermine the motivation for the feature.

Thank you, i understand.

**Comment by huikmn** [comment]
> Even with that constraint, wouldn't the widening instructions like vwadd still be able to produce a result that required 2 registers to hold the result?

yes, it still have the problem, but maybe for this kind of instruction, i can make vlen <= vlen/sew/2, or split the instruction. Either way, it's much simpler than calculating all exception and number of uops for all instructions
