### ISSUE TITLE
Should illegal instruction exception be raised for unsupported EEW?

### ISSUE THREAD

**Issue by jlong299** [riscv/riscv-v-spec#817]
For single-letter "V" extension, the EEW = 128 is not supported. So if a widening instruction (SEW=64) with output EEW = 128 comes, which of below should I do?
(1) Raise a exception of illegal instruction
OR
(2) Just execute it and write back register file with a likely incorrect value

**Comment by aka2en** [comment]
It's an illegal instruction exception if SEW=128-bit is not supported in the machine

**Comment by jlong299** [comment]
Thank you so much.
