### ISSUE TITLE
Unable to understand Vector Element Index Instruction  

### ISSUE THREAD

**Issue by balaji-ch** [riscv/riscv-v-spec#829]
The spec says

The `vid.v` instruction writes each element’s index to the destination vector register group, from 0 to vl-1.
`vid.v vd, vm # Write element ID to destination.`

What element's indexes are written into destination register ?

**Comment by nick-knight** [comment]
Informally, it writes `0,1,2,3,4,...` to the destination register, one integer per destination element.

**Comment by balaji-ch** [comment]
What is the source here?

**Comment by nick-knight** [comment]
The source vector? None. You can view it as a nullary operation (ignoring masking, `vl`, etc.).
