### ISSUE TITLE
Basic questions about masks

### ISSUE THREAD

**Issue by benjaminou4412** [riscv/riscv-v-spec#830]
Hello! Apologies in advance - I'm a complete beginner at vector architectures and RVV, so my questions are probably a little too basic for this forum (I'd be open to posting elsewhere, but I'm not sure where to ask these sorts of "correct my understanding" things; do point me to a more appropriate place if there is one). With that said, here are my questions:

1. The spec states "The mask value used to control execution of a masked vector instruction is always supplied by vector register v0." Does this mean v0's sole use is as the mask register, or can it be used as a general-purpose vector register for unmasked execution? (I assume it can, I'm just being thorough). 
2. Does the above mean no other vector registers can ever supply mask bits? There is a clarification that only a single mask register currently exists for encoding space reasons and that future extensions may allow for specifying other mask registers, but in Section 15 ("Vector Mask Instructions"), the mask instructions definitionally seem to operate on multiple separate mask registers.
3. Just to be completely clear, when the spec states "Masked vector stores only update active memory elements", that means that inactive vector elements in the source register for a vector store do not get sent to memory in any way, correct?

**Comment by aswaterman** [comment]
v0 is just a regular vector register, so it can be used to hold values other than masks in other contexts.

Other registers can be used to temporarily hold masks, but they cannot supply masks to instructions. Need to move to v0 first.

Yes to 3.
