### ISSUE TITLE
How to set Rounding modes in frm fields ?

### ISSUE THREAD

**Issue by balaji-ch** [riscv/riscv-v-spec#831]
In 13.17. Single-Width Floating-Point/Integer Type-Convert Instructions
 The conversions use the dynamic rounding mode in **frm**, except for the `rtz `variants, which round towards zero.
 
 How to set the rounding modes ? 

I would like to truncate a floating point to integer. For example,
a float -42.7 to -42

but 
`vfcvt.rtz.x.f.v  vd, vs2, vm   # Convert float to signed integer, truncating.`
`rtz` is truncating it to 0 in spike simulator and 

`vfcvt.rtz.x.f.v  vd, vs2, vm` converts to nearest integer.

**Comment by balaji-ch** [comment]
@nick-knight  thank you. I am not interested in Intrinsic but inline assembly.

according to this https://www.andestech.com/wp-content/uploads/Andes-RVV-Webinar-II_final.pdf
there are [2:0] modes in 
![image](https://user-images.githubusercontent.com/64900601/194608383-ecea4dda-6461-4af7-9fa8-20119969c1d7.png)
Could you please tell what modes correspond to what values ?
Or is it same like vxrm modes ?

>>I don't understand the rest of your post: what is the perceived issue?
rtz mode is making -ve floats to zero and default rounding is not truncating in spike simulator.

**Comment by nick-knight** [comment]
Please refer to Table 13.1 in `riscv-spec.pdf`: https://github.com/riscv/riscv-isa-manual/releases

**Comment by nick-knight** [comment]
If negative floats less than `-0.5` are being returned as integer zero, I'd suggest double-checking your assembly code to make sure you are using the signed version of the conversions, rather than the unsigned versions. I just looked at the Spike implementation, and it appears to be invoking SoftFloat for this functionality, so if there is indeed a bug here then please report it.

**Comment by balaji-ch** [comment]
> Please refer to Table 13.1 in `riscv-spec.pdf`: https://github.com/riscv/riscv-isa-manual/releases

Thank you. the RVV spec could have linked to this section.
