### ISSUE TITLE
Question about e8 mf8 in zve32x

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv/riscv-v-spec#832]
Suppose we have a RVV CPU with VLEN = 32.

My understanding when this CPU receive the following instructions:
vsetvl a5, zero, e8, m1....  The value of a5 should be 4.
vsetvl a5, zero, e8, mf4....  The value of a5 should be 1.
1.What about vsetvl a5, zero, e8, mf8 ?  How does this CPU with VLEN =32 response to this instruction ?
Randomly put a meaningless value into "a5" ? Or report an illegal instruction ?

2. If CPU report an illegal instruction. 
   Is it a good idea that compiler report an error 
   when user compiles an intrinsic like "vsetvl_e8mf8 (a)" with -march=rv32gc_zve32x 
   rather than just simpily generates the instruction ?

Thanks.

**Comment by aswaterman** [comment]
The answer to (1) is that it is reserved to use an LMUL that would result in a VLMAX less than 1. The recommendation is that you set vill=1 in such reserved cases.

I have no comment on the second question, but it is not an ISA spec question, so I am closing this issue.
