### ISSUE TITLE
What value should be written for vector mask register bits > VLMAX？ 

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-v-spec#833]
In riscv-v-spec, tail element is defined as tail(x) = (vl <= x < max(VLMAX,VLEN/SEW)).
For example, if VLEN = 128, lmul = 1, sew = 8, vl = 10, then VLMAX = 16, tail elements should be [10:15]. 
For vmseq v1, v2, v3，what value should be written in v1[16:127]？

**Comment by aka2en** [comment]
vmseq is enforced tail-agnostic policy, so you could either write 1s or keep original bits.

**Comment by jinyinghan324** [comment]
Thank you for your replay
