### ISSUE TITLE
Are "NOTE" sections normative?

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv/riscv-v-spec#839]
There's a handful of these "NOTE: ${TEXT}" blocks in the V spec.  Not sure what to make of them.

**Comment by aswaterman** [comment]
They’re supposed to serve the same purpose as the commentary blocks in the LaTeX specs.

**Comment by palmer-dabbelt** [comment]
Thanks.

**Comment by aswaterman** [comment]
You're welcome!
