### ISSUE TITLE
signed/unsigned immediate field

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#84]
Section 11 shows the instruction formats, and shows OPIVI as having a simm5 field.  Section 11.1 shows simm[4:0] for the OPIVI funct3 value.  In section 11.1, the line number 1 says that the immediate field is sign extended.

However, vslideup, vslidedown, and vrgather take an unsigned immediate, and use the OPIVI encoding.

Also, the vector shift instructions use the immediate as unsigned, though that case is a little more complicated as shifts only use log2(SEW) bits of the immediate, so it is really only unsigned for SEW>=32, but I think it would be simpler to say that these use unsigned immediate fields also.

**Comment by kasanovic** [comment]
OK - fixed text to be clearer that immediate could be signed or unsigned.
