### ISSUE TITLE
For vsetvl, if the high bits of value in rs2 are not zero, should vill be set?

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-v-spec#847]
The width of vtype is 8. If rs2[63:8](XLEN = 64) is not zero, should vill be set and vtype be cleared? Or should high bits be ignored？

**Comment by aswaterman** [comment]
The spec says, "If the vtype value is not supported by the implementation, then the vill bit is set in vtype".  vsetvl is no different than vsetvli in this regard--all bits of rs2 must be considered.
