### ISSUE TITLE
If design does not support half-presion floating-point, should vfncvt.x.f.w of e16 be supported?

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-v-spec#851]
If design does not support half-presion floating-point, e16 is not supported for most vector floating-point instructions. But I am not sure about whether vfncvt.x.f.w should be supported, because it converts 32-bit floating-point to 16-bit integer, no 16-bit floating-point is involved.

**Comment by aswaterman** [comment]
`vfncvt.x.f.w` should still be supported; it is unrelated to Zvfh.

**Comment by jinyinghan324** [comment]
Thank you!
