### ISSUE TITLE
Is a non-power-of-2 vlenb allowed?

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv/riscv-v-spec#864]
This came up in passing on a QEMU review <https://lore.kernel.org/r/mhng-348cd335-c03c-481a-b09f-06bb3134650f@palmer-ri-x1c9a/>.  I'd been assuming that `vlenb` is a power of two, but I don't see anything in the spec that says so.  I'm not sure if I'm missing something?

**Comment by nick-knight** [comment]
> The number of bits in a single vector register, VLEN ≥ ELEN, which must be a power of 2, and must be no greater than 216.

**Comment by aswaterman** [comment]
IOW, yes, the spec says it must be a power of two.

**Comment by palmer-dabbelt** [comment]
Thanks, I guess I just wasn't paying attention -- I was only looking for vlenb.
