### ISSUE TITLE
Question about vstart?

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-v-spec#866]
Our implementation will never take interrupts during any vector instruciotn, including vector reduction, permutation, mask instructions. Is is permitted to raise an illegal instruction exception when attemptin to exectue any vector instruction when vstart is nonzero?

**Comment by aka2en** [comment]
Yes, it is permitted. Check spec:
```
Implementations are permitted to raise illegal instruction exceptions when attempting to execute a vector instruction with a value of vstart that the implementation can never produce when executing that same instruction with the same vtype setting.
```

**Comment by huangxiansheng123** [comment]
![clipbord_1678674467039](https://user-images.githubusercontent.com/53940249/224618394-8c511d1d-7d81-4e6d-973c-674b19519d5e.png)
Does it also include the vmv.x.s instruction? @aka2en

**Comment by nick-knight** [comment]
Yes: according to my reading of the spec, there are no exceptions to the provision that @aka2en quoted.
