### ISSUE TITLE
Question about load mask

### ISSUE THREAD

**Issue by RuHungLee** [riscv/riscv-v-spec#869]
I would like to use RVV intrinsics to load an immediate value into a mask register ( v0 ). However, in the specification, I only see intrinsics for loading values from memory into a mask register ( vlm ). Is there an intrinsic available for loading an immediate value into a mask register?

**Comment by nick-knight** [comment]
This is the ISA spec. The C intrinsics spec is https://github.com/riscv-non-isa/rvv-intrinsic-doc
