### ISSUE TITLE
vslte and vsgte

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#88]
The document defines a vsle instruction, and then says that vsgte is a pseudo instruction for vslte, which is inconsistent.   vsle appears 11 times, vslte appears 5 times.  vsge appears 0 times, and vsgte appears 12 times.  I'd prefer that either vsle/vsge or vslte/vsgte be used for consistency.

**Comment by kasanovic** [comment]
should be vsle/vge - this matches scalar ISA branch syntax. Fixing.
