### ISSUE TITLE
Question about setting spike

### ISSUE THREAD

**Issue by huikmn** [riscv/riscv-v-spec#888]
We are using the latest spike: Spike RISC-V ISA Simulator 1.1.1-dev as our reference mode. In our design, we choose all 1s as our agnostic policy for masked and tail elements. But the spike seems choose undisturbed as default, and we haven't find any settings to change this. So out result comparesion is always wrong. Is there any way to change the agnostic policy of spike to all 1s? Thank you!

**Comment by furuame** [comment]
The proper place to file this request is https://github.com/riscv-software-src/riscv-isa-sim

**Comment by huikmn** [comment]
> The proper place to file this request is https://github.com/riscv-software-src/riscv-isa-sim

ok, thanks, i wll ask again
