### ISSUE TITLE
Is NF=1 for segment load/store banned?

### ISSUE THREAD

**Issue by xhebox** [riscv/riscv-v-spec#892]
While experimenting with rvv, I found that there are just no `vlseg1xxx` instructions in gcc. There are cases of `NF=2~8`, though.

Check https://github.com/bminor/binutils-gdb/blob/a89e364b45a93acd20f48abd787ef5cb7c07f683/opcodes/riscv-opc.c#LL1112C2-L1112C8

I understand that `NF=1` is equal to normal load/store... So are these instruction reserved, must be implemented, or ... ?

**Comment by topperc** [comment]
I think the instructions encodings where NF=1 are the encodings for the normal load/store instructions.

**Comment by xhebox** [comment]
Thanks, @topperc . I see, they share the same encodings.
