### ISSUE TITLE
question about setting vl

### ISSUE THREAD

**Issue by huikmn** [riscv/riscv-v-spec#895]
According to Vector ISA, when use x0 as both rd and rs for VSETVL instruction, VL value should keep existing value.
<img width="731" alt="image" src="https://github.com/riscv/riscv-v-spec/assets/110142725/ae785c31-1402-4b52-9a49-6f745c7a218d">
But what if the new VTYPE setting makes new VLMAX < existing vl? In the ISA, this situation shoule be reserved.
<img width="723" alt="image" src="https://github.com/riscv/riscv-v-spec/assets/110142725/a887a21f-ed24-4b23-8534-35ade3ea26e9">
So a exception should be detected? or at least VILL in VTYPE shoule be set?
But we ran this case in SPIKE. Our VLEN is 256.
![image](https://github.com/riscv/riscv-v-spec/assets/110142725/88a86b9f-4c44-4b9e-a0bb-e482add6cbc5)
It turns out there is no exception raised and VL became new VLMAX. Is there a condradiction between ISA and SPIKE? Which one we should follow? Thanks.

**Comment by aswaterman** [comment]
There's no contradiction.  Reserved means the implementation can choose the behavior (with illegal-instruction exception being one of the choices).

**Comment by huikmn** [comment]
So you means this reserved situation, every solution is acceptable. Spike chooses one solution doesn't means other ways is wrong. But if we use Spike as our reference mode, we better use the same choice as Spike. Do i undertand it correctly?

**Comment by aswaterman** [comment]
I'd actually recommend raising an exception in this case.  For the time being, I suggest manually modifying Spike, since we don't yet have a good general way of configuring these implementation-specific behaviors.

**Comment by huikmn** [comment]
OK，Thank you very much!
