### ISSUE TITLE
Question about Narrowing Floating-Point/Integer Type-Convert Instructions

### ISSUE THREAD

**Issue by bhbruce** [riscv/riscv-v-spec#899]
Do these instructions support `float to uint16/int16 conversion`?

Section [13.19](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#1319-narrowing-floating-pointinteger-type-convert-instructions) mentions that:
     `A set of conversion instructions is provided to convert wider integer and floating-point datatypes to a type of half the width.`. 

I suppose it supports `float to uint16/int16 conversion`.
However, the example below doesn't mention it.
So I would like to confirm whether these instructions support `float to uint16/int16 conversion`.

**Comment by furuame** [comment]
Yes I think so

**Comment by WojciechMula** [comment]
They support f32 -> i16 and also f16 -> i8. I don't see any restrictions in the spec.
