### ISSUE TITLE
When vstart is not 0, is the execution of the vset{i}vl{i} command handled according to the illegal command exception?

### ISSUE THREAD

**Issue by Wei-VV1995** [riscv/riscv-v-spec#903]
"Implementations are permitted to raise illegal instruction exceptions when attempting to execute a vector instruction with a value of vstart that the implementation can never produce when executing that same instruction with the same vtype setting."
When vstart is not 0, is the execution of the vset{i}vl{i} command handled according to the illegal command exception？

**Comment by aswaterman** [comment]
No. the instruction should execute as normal (and set vstart to 0 as a side effect).
