### ISSUE TITLE
vsetvli/vsetivli encoding

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-v-spec#905]
The zimm field in the vsetvli instruction is 11-bits wide.  Only the least sig 8 bits are used to encode the vtype information.  What happens if the most significant 3 bits are non-zero?  Does the instruction become illegal?

**Comment by aswaterman** [comment]
It's the same as using `vsetvl` with an rs2 argument that holds an invalid vtype setting.  See https://github.com/riscv/riscv-v-spec/blob/919336a7210597231c6efbec97b7e9fedfa5a9f8/v-spec.adoc#611-unsupported-vtype-values

**Comment by jrahmeh** [comment]
Thank you.
