### ISSUE TITLE
vsgte.vx pseudoinstruction

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#91]
For unknown x, the 3rd option says
masked va >= x, vd == v0
but there is nothing here that requires vd == v0, I think this option should be allowed when vd is unknown even if it happens to be the same value as v0.  If vd is known and != v0, then you can use the 2nd option.  But if vd is unknown then you can use the 3rd option.

The 3rd option does require that the vt temp register != v0, which isn't documented.

**Comment by kasanovic** [comment]
Will change comment on third case to indicate arbitrary vd.
Will add description of temp register on pseudo instruction.
