### ISSUE TITLE
Issue in Constraints on Setting vl

### ISSUE THREAD

**Issue by latifbhatti** [riscv/riscv-v-spec#918]
I have complete riscv base extension with 5 stage pipeline swallow core(written in CHISEL). now, I add vector extension in single cycle swallow core.
vl CSR can only be updated by the vset{i}vl{i} instructions, and the fault-only- first vector load instruction variants. I known that when AVL ≤ VLMAX , then value of vl is equal to AVL(value of AVL comes from rs1 data) and other remaining bits working as tail part. but I can not understand the point of 2 and 3 mention in section of 6.3.

**Comment by nick-knight** [comment]
I find Section 6.3 to be perfectly clear; what specifically is the issue?

For a simple implementation, I would suggest taking vl = min(AVL, VLMAX).

**Comment by latifbhatti** [comment]
when addi x4 ,x0,5
vsetvli x5,x4 , e8,m1,tu,mu
vlmax=16 and avl = 5  then vl = 5
but
According to these assembly instructions, with addi x4, x0, 20 and vsetvli x5, x4, e8, m1, tu, mu, when VLMax is 16 and AVL is 20, what value will be in the VL CSR?

**Comment by aswaterman** [comment]
The relevant constraint is `ceil(AVL / 2) ≤ vl ≤ VLMAX if AVL < (2 * VLMAX)` -- i.e. some value between 10 and 16.

**Comment by latifbhatti** [comment]
Thanks @aswaterman and @nick-knight
