### ISSUE TITLE
Main README dead link

### ISSUE THREAD

**Issue by lianakoleva** [riscv/riscv-v-spec#926]
"GNU toolchain port for v0.8" points to https://github.com/riscv-collab/riscv-gnu-toolchain/tree/rvv-0.8.x, which is no longer a branch of the repo.

**Comment by aswaterman** [comment]
If you don't mind making a PR that fixes the broken link, we'll happily merge it.

**Comment by lianakoleva** [comment]
I'm not sure what it should be replaced with. All RVV branches have been deleted from that repo. See [riscv-gnu-toolchain/PR1308](https://github.com/riscv-collab/riscv-gnu-toolchain/issues/1308) for the discussion.

**Comment by aswaterman** [comment]
I don't know how to address this issue if we don't know how to update the README.  Feel free to submit a PR that deletes the offending link.  Closing in the interim.
