### ISSUE TITLE
Is vxsat raised based on pre-round or post-route result for vnclip?

### ISSUE THREAD

**Issue by liangkaiwang** [riscv/riscv-v-spec#936]
Let's say we operate on SEW32, and the input is a 64b 0xfffffffeffffffff
And the right shift amount is 1, and the rounding mode is RUP, do we raise vista? 

If I represent this in decimal value, the input is 
-2^33 + (2^32-1).
so by right shifting with 1, we have  -2^32 + 2^31 - 0.5 = -2^31 - 0.5
This is bigger than the max negative in the destination format. Even though with RUP, the -0.5 is throw away and the "rounded" result is 2^-31, which is "in-range", I feel that we should still raise vxsat in this case. Am I correct?

**Comment by liangkaiwang** [comment]
cc @aswaterman

**Comment by aswaterman** [comment]
"the shifted rounded source value [...] saturates if the result would overflow the destination" -- i.e., if the rounded result fits, it is not considered to saturate.

**Comment by liangkaiwang** [comment]
Thanks. I agree with the interpretation with the text. I guess I just wish I was in the discussion when it was first created.

thanks
Liang-Kai
