### ISSUE TITLE
Add clarification regarding supported index value of indexed load/stores

### ISSUE THREAD

**Issue by troibe** [riscv/riscv-v-spec#941]
In section `Vector Strided Instructions` it is stated that

> Negative and zero strides are supported.

After implementing the strided loads I naively assumed that indexed load/stores also allow negative and zero indices.
When [comparing my simulator results with Spike](https://github.com/ksco/riscv-vector-tests) I realized that Spike only supports zero and positive indices,
which I assume is the correct implementation.

Would it be possible to add something along the lines of 

> Only zero and positive indices are supported.

to the `Vector Indexed Instructions` section?

**Comment by aswaterman** [comment]
I think this follows from the remark that "If the vector offset elements are narrower than XLEN, they are zero-extended to XLEN before adding to the base effective address."
