### ISSUE TITLE
Mask instruction tail elements behavior issue(while vl=0)

### ISSUE THREAD

**Issue by TogashiHan** [riscv/riscv-v-spec#944]
Hi, I'd like to confirm the vector mask instructions **tail** behavior while no body elements(to be specific, while **vl=0**).

In RV-V spec v1.0 Chapter 5, 5.4, we have the definition of the all kinds of elements behavior:
that "when vstart >= vl / **vl =0**, **no elements**, including tail elements **are updated** in any **destination** vector register group".
So in almost all the vector arith instructions, when we set the vl = 0(by vset), we expect that even we set tail as agnostic, the spike simulator result should not update the destination vector reigsters.
![企业微信截图_17092851049506](https://github.com/riscv/riscv-v-spec/assets/119928506/9243b7dd-c8b5-48b3-a238-8c2019d5b434)

However, in Chapter15 says:
"**Tail** elements are **always updated** with ta policy"
![企业微信截图_17092854619222](https://github.com/riscv/riscv-v-spec/assets/119928506/fb19b878-cb9f-4194-8c03-362ae001bee0)

So the question is that **while vl=0** should the vector mask instruction tail elements follow the RV-V Spec Chapter5.4 definition "no elements, including agnostic elements are updated in vector destination register group"
or follow the Chapter15 definition "tail elements are always updated with ta policy"?

FYI: 
Spike result(follow Chapter 15, our **ta policy** is **update with all '1**)
![d816ffd2f6313bc95a5220b12c6e4a5](https://github.com/riscv/riscv-v-spec/assets/119928506/61be8181-aeb8-4373-af5e-89dce3270d10)

ASM code
![企业微信截图_17092876735350](https://github.com/riscv/riscv-v-spec/assets/119928506/2c750fb6-5031-4d06-afb3-9d85c9c830cf)

**Comment by furuame** [comment]
It's the latter one. The style of spec writing specifies the general rule first, but describes other rules on the specific instructions.

**Comment by TogashiHan** [comment]
Much appreciated.
