### ISSUE TITLE
reductions should use consistent operation for accumulation?

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#95]
This is from Thang at Andes on the mailing list.

Section 15.1, except for VREDSUM, should other instructions use the same operator as vs2[i] for vs1[0]? 
vredand.vs  vd, vs2, vs1, vm   # vd[0] =  and_i( vs2[i] ) + vs1[0]
--> vredand.vs  vd, vs2, vs1, vm   # vd[0] =  and_i( vs2[i] ) AND vs1[0]
VREDAND should "AND" with vs1[0] instead of "+"

**Comment by David-Horner** [comment]
This is also applicable to the other aggregating functions.

Perhaps this form:

Agg_op  ( vs2[*], vs1[0] ) ; where * denotes all active elements could be used.

**Comment by kasanovic** [comment]
Fixed for #98
