### ISSUE TITLE
Any vw4* instructions?

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-v-spec#97]
In section 11.2, the following paragraph mentioned about **vw4*** instructions:

> For integer multiply-add, another widening option increases the size of the accumulator to **4*SEW**
(i.e., **4*SEW** += **SEW*SEW**). These are distinguished by a **vw4*** prefix on the opcode.

However, I cannot find any instruction with this vw4* prefix. Are these instructions missing or removed from the specification?

**Comment by kasanovic** [comment]
This was left over text. They were removed from base spec for now. I changed text to a note about their possible later inclusion.
