### ISSUE TITLE
inconsistent use of &le; and <=

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#99]
Some but not all uses of <= were changed to &le; (ampersand le;) to prevent them from displaying as a left arrow.  But now we have inconsistent usage as the two choices are rendered differently in html.  We might also want to change >= for consistency.

**Comment by aswaterman** [comment]
I can't assign you to review using the github UI.  OK with https://github.com/riscv/riscv-v-spec/pull/100 ?

**Comment by jim-wilson** [comment]
Yes, it looks OK, though I managed to find another spec typo while trying to look at only the <= and >= stuff.

**Comment by aswaterman** [comment]
Alright, closing this one.
